//
//  DesignTokens.swift
//  Drawgle Auto-generated
//

import SwiftUI

struct AppTheme {
    static let backgroundPrimary = Color(hex: "#FFFFFF")
    static let backgroundSecondary = Color(hex: "#F3F4F6")
    static let surfaceCard = Color(hex: "#FFFFFF")
    static let actionPrimary = Color(hex: "#3B82F6")
    static let actionOnPrimary = Color(hex: "#FFFFFF")
    static let textHigh = Color(hex: "#111827")
    static let textMedium = Color(hex: "#4B5563")
    static let textLow = Color(hex: "#9CA3AF")
    static let borderDivider = Color(hex: "#E5E7EB")
    
    static let borderRadiusApp: CGFloat = 18
    static let borderRadiusPill: CGFloat = 9999.0
    
    static let screenPadding: CGFloat = 24
    static let sectionGap: CGFloat = 24
    static let elementGap: CGFloat = 16
}

extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 3: // RGB (12-bit)
            (a, r, g, b) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: // RGB (24-bit)
            (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: // ARGB (32-bit)
            (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (a, r, g, b) = (255, 0, 0, 0)
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue:  Double(b) / 255,
            opacity: Double(a) / 255
        )
    }
}

//
//  JournalView.swift
//  Auto-generated by Drawgle
//

import SwiftUI
// Requires: https://github.com/lucide-icons/lucide-swift

struct JournalView: View {
    var body: some View {
        ZStack(alignment: .bottom) {
            ScrollView {
    VStack(alignment: .leading) {
        VStack(alignment: .leading) {
            VStack(alignment: .leading) {
                Text("Journal")
                    .font(.system(size: 24))
                    .fontWeight(.bold)
                    .padding(.bottom, AppTheme.sectionGap)
                VStack(alignment: .leading) {
                    HStack() {
                        HStack() {
                            HStack() {
                                LucideView(icon: .flame) // Lucide: flame
                                    .frame(width: 20, height: 20)
                            }
                            .background(AppTheme.backgroundPrimary)
                            .cornerRadius(9999)
                            .frame(width: 36, height: 36)
                            VStack(alignment: .leading) {
                                Text("Calories")
                                    .font(.system(size: 18))
                                    .fontWeight(.bold)
                                Text("Week Days")
                                    .font(.system(size: 12))
                                    .fontWeight(.semibold)
                            }
                        }
                        Spacer()
                        Button(action: {
                            // Action here
                        }) {
                            HStack() {
                                LucideView(icon: .calendar) // Lucide: calendar
                                    .frame(width: 20, height: 20)
                            }
                            .padding(.vertical, 12)
                            .padding(.horizontal, 16)
                            .background(AppTheme.backgroundPrimary)
                            .cornerRadius(9999)
                        }
                    }
                    VStack(alignment: .leading) {
                        HStack() {
                            Text("Consumed")
                                .font(.system(size: 16))
                                .fontWeight(.medium)
                            Spacer()
                            Text("00 cal")
                                .font(.system(size: 32))
                                .fontWeight(.bold)
                        }
                        .padding(.top, 12)
                        .padding(.bottom, 12)
                        .background(AppTheme.backgroundPrimary)
                        .cornerRadius(20)
                        HStack() {
                            Text("Remaining")
                                .font(.system(size: 16))
                                .fontWeight(.medium)
                            Spacer()
                            Text("00 cal")
                                .font(.system(size: 32))
                                .fontWeight(.bold)
                        }
                        .padding(.top, 12)
                        .padding(.bottom, 12)
                        .background(AppTheme.backgroundPrimary)
                        .cornerRadius(20)
                        ZStack(alignment: .topLeading) {
                            Rectangle().fill(Color.clear)
                            .background(
                                Canvas { context, size in
                                    let stripeWidth: CGFloat = 6
                                    let totalWidth = size.width + size.height
                                    var x: CGFloat = 0
                                    while x < totalWidth {
                                        var path = Path()
                                        path.move(to: CGPoint(x: x, y: 0))
                                        path.addLine(to: CGPoint(x: x + stripeWidth, y: 0))
                                        path.addLine(to: CGPoint(x: x - size.height + stripeWidth, y: size.height))
                                        path.addLine(to: CGPoint(x: x - size.height, y: size.height))
                                        path.closeSubpath()
                                        context.fill(path, with: .color(Color(red: 0/255.0, green: 0/255.0, blue: 0/255.0).opacity(0.03)))
                                        x += stripeWidth * 2
                                    }
                                }
                                .background(AppTheme.borderDivider)
                            )
                            HStack() {
                                Text("Remaining")
                                    .font(.system(size: 16))
                                    .fontWeight(.medium)
                                Spacer()
                                Text("00 cal")
                                    .font(.system(size: 32))
                                    .fontWeight(.bold)
                            }
                        }
                        .padding(.top, 12)
                        .padding(.bottom, 12)
                        .background(AppTheme.backgroundPrimary)
                        .cornerRadius(20)
                    }
                    HStack() {
                        VStack(alignment: .center) {
                            ZStack(alignment: .topLeading) {
                                HStack() {
                                    LucideView(icon: .wheat) // Lucide: wheat
                                        .frame(width: 20, height: 20)
                                }
                                VStack(alignment: .leading) {
                                    ZStack {
                                        Circle()
                                            .stroke(AppTheme.backgroundPrimary, lineWidth: 6)
                                        Circle()
                                            .trim(from: 0, to: 0.00)
                                            .stroke(Color(hex: "#FFFFFF"), style: StrokeStyle(lineWidth: 6, lineCap: .round))
                                    }
                                    .frame(width: 48, height: 48)
                                }
                            }
                            .frame(width: 64, height: 64)
                            VStack(alignment: .leading) {
                                Text("0/150")
                                Text("gr")
                                    .font(.system(size: 12))
                            }
                            Text("Power Carbs")
                                .font(.system(size: 12))
                                .fontWeight(.semibold)
                                .padding(.top, 2)
                        }
                        .frame(maxWidth: .infinity)
                        Spacer()
                        VStack(alignment: .center) {
                            ZStack(alignment: .topLeading) {
                                HStack() {
                                    LucideView(icon: .egg) // Lucide: egg
                                        .frame(width: 20, height: 20)
                                }
                                VStack(alignment: .leading) {
                                    ZStack {
                                        Circle()
                                            .stroke(AppTheme.backgroundPrimary, lineWidth: 6)
                                        Circle()
                                            .trim(from: 0, to: 0.00)
                                            .stroke(Color(hex: "#FFFFFF"), style: StrokeStyle(lineWidth: 6, lineCap: .round))
                                    }
                                    .frame(width: 48, height: 48)
                                }
                            }
                            .frame(width: 64, height: 64)
                            VStack(alignment: .leading) {
                                Text("0/113")
                                Text("gr")
                                    .font(.system(size: 12))
                            }
                            Text("Protein Power")
                                .font(.system(size: 12))
                                .fontWeight(.semibold)
                                .padding(.top, 2)
                        }
                        .frame(maxWidth: .infinity)
                        Spacer()
                        VStack(alignment: .center) {
                            ZStack(alignment: .topLeading) {
                                HStack() {
                                    LucideView(icon: .droplet) // Lucide: droplet
                                        .frame(width: 20, height: 20)
                                }
                                VStack(alignment: .leading) {
                                    ZStack {
                                        Circle()
                                            .stroke(AppTheme.backgroundPrimary, lineWidth: 6)
                                        Circle()
                                            .trim(from: 0, to: 0.00)
                                            .stroke(Color(hex: "#FFFFFF"), style: StrokeStyle(lineWidth: 6, lineCap: .round))
                                    }
                                    .frame(width: 48, height: 48)
                                }
                            }
                            .frame(width: 64, height: 64)
                            VStack(alignment: .leading) {
                                Text("0/50")
                                Text("gr")
                                    .font(.system(size: 12))
                            }
                            Text("Healthy Fat")
                                .font(.system(size: 12))
                                .fontWeight(.semibold)
                                .padding(.top, 2)
                        }
                        .frame(maxWidth: .infinity)
                    }
                }
                .background(AppTheme.surfaceCard)
                .cornerRadius(AppTheme.borderRadiusApp)
                LazyVGrid(columns: Array(repeating: GridItem(.flexible(), spacing: AppTheme.elementGap), count: 2), spacing: AppTheme.elementGap) {
                    VStack(alignment: .leading) {
                        HStack(alignment: .top) {
                            AsyncImage(url: URL(string: "https://pub-7c8c3c7444724a39ba3eeb8accbbca4a.r2.dev/visual-assets/b8041495-1552-4079-9c20-80bd656e240f/display_1024.png")) { image in
                                image.resizable()
                                    .aspectRatio(contentMode: .fill)
                            } placeholder: {
                                Color.gray.opacity(0.1)
                            }
                            .frame(width: 44, height: 44)
                            .cornerRadius(9999)
                            Spacer()
                            Text("631 kcal")
                                .font(.system(size: 14))
                                .fontWeight(.regular)
                        }
                        Spacer()
                        HStack() {
                            Text("Breakfast")
                                .font(.system(size: 16))
                                .fontWeight(.medium)
                            Spacer()
                            Button(action: {
                                // Action here
                            }) {
                                HStack() {
                                    LucideView(icon: .plus) // Lucide: plus
                                        .frame(width: 20, height: 20)
                                }
                                .padding(.vertical, 12)
                                .padding(.horizontal, 16)
                                .background(Color(hex: "#FFFFFF"))
                                .cornerRadius(9999)
                            }
                        }
                    }
                    .background(Color(hex: "#FFFFFF"))
                    .cornerRadius(AppTheme.borderRadiusApp)
                    .frame(minHeight: 120)
                    VStack(alignment: .leading) {
                        HStack(alignment: .top) {
                            HStack() {
                                LucideView(icon: .salad) // Lucide: salad
                                    .frame(width: 20, height: 20)
                            }
                            .cornerRadius(9999)
                            .frame(width: 44, height: 44)
                            Spacer()
                            Text("486 kcal")
                                .font(.system(size: 14))
                                .fontWeight(.regular)
                        }
                        Spacer()
                        HStack() {
                            Text("Lunch")
                                .font(.system(size: 16))
                                .fontWeight(.medium)
                            Spacer()
                            Button(action: {
                                // Action here
                            }) {
                                HStack() {
                                    LucideView(icon: .plus) // Lucide: plus
                                        .frame(width: 20, height: 20)
                                }
                                .padding(.vertical, 12)
                                .padding(.horizontal, 16)
                                .background(Color(hex: "#FFFFFF"))
                                .cornerRadius(9999)
                            }
                        }
                    }
                    .background(Color(hex: "#FFFFFF"))
                    .cornerRadius(AppTheme.borderRadiusApp)
                    .frame(minHeight: 120)
                    VStack(alignment: .leading) {
                        HStack(alignment: .top) {
                            HStack() {
                                LucideView(icon: .soup) // Lucide: soup
                                    .frame(width: 20, height: 20)
                            }
                            .cornerRadius(9999)
                            .frame(width: 44, height: 44)
                            Spacer()
                            Text("359 kcal")
                                .font(.system(size: 14))
                                .fontWeight(.regular)
                        }
                        Spacer()
                        HStack() {
                            Text("Dinner")
                                .font(.system(size: 16))
                                .fontWeight(.medium)
                            Spacer()
                            Button(action: {
                                // Action here
                            }) {
                                HStack() {
                                    LucideView(icon: .plus) // Lucide: plus
                                        .frame(width: 20, height: 20)
                                }
                                .padding(.vertical, 12)
                                .padding(.horizontal, 16)
                                .background(Color(hex: "#FFFFFF"))
                                .cornerRadius(9999)
                            }
                        }
                    }
                    .background(Color(hex: "#FFFFFF"))
                    .cornerRadius(AppTheme.borderRadiusApp)
                    .frame(minHeight: 120)
                    VStack(alignment: .leading) {
                        HStack(alignment: .top) {
                            HStack() {
                                LucideView(icon: .cookie) // Lucide: cookie
                                    .frame(width: 20, height: 20)
                            }
                            .cornerRadius(9999)
                            .frame(width: 44, height: 44)
                            Spacer()
                            Text("193 kcal")
                                .font(.system(size: 14))
                                .fontWeight(.regular)
                        }
                        Spacer()
                        HStack() {
                            Text("Snack")
                                .font(.system(size: 16))
                                .fontWeight(.medium)
                            Spacer()
                            Button(action: {
                                // Action here
                            }) {
                                HStack() {
                                    LucideView(icon: .plus) // Lucide: plus
                                        .frame(width: 20, height: 20)
                                }
                                .padding(.vertical, 12)
                                .padding(.horizontal, 16)
                                .background(Color(hex: "#FFFFFF"))
                                .cornerRadius(9999)
                            }
                        }
                    }
                    .background(Color(hex: "#FFE0B2"))
                    .cornerRadius(AppTheme.borderRadiusApp)
                    .frame(minHeight: 120)
                }
            }
            .padding(.horizontal, AppTheme.screenPadding)
        }
        .padding(.top, 16)
        .padding(.bottom, 96)
        .frame(maxWidth: .infinity)
    }
    .background(AppTheme.backgroundPrimary)
    .frame(maxWidth: .infinity)
    .foregroundColor(AppTheme.textHigh)
            }
    VStack(alignment: .leading) {
        HStack() {
            Button(action: {
                // Action here
            }) {
                HStack() {
                    LucideView(icon: .chefHat) // Lucide: chef-hat
                        .frame(width: 20, height: 20)
                }
                .padding(.vertical, 12)
                .padding(.horizontal, 16)
            }
            .frame(maxWidth: .infinity)
            Button(action: {
                // Action here
            }) {
                HStack() {
                    LucideView(icon: .calendarDays) // Lucide: calendar-days
                        .frame(width: 20, height: 20)
                }
                .padding(.vertical, 12)
                .padding(.horizontal, 16)
            }
            .frame(maxWidth: .infinity)
            Button(action: {
                // Action here
            }) {
                HStack() {
                    LucideView(icon: .sparkles) // Lucide: sparkles
                        .frame(width: 20, height: 20)
                }
                .padding(.vertical, 12)
                .padding(.horizontal, 16)
            }
            .frame(maxWidth: .infinity)
            Button(action: {
                // Action here
            }) {
                HStack() {
                    HStack() {
                        LucideView(icon: .bookOpen) // Lucide: book-open
                            .frame(width: 20, height: 20)
                    }
                    .background(AppTheme.actionPrimary)
                    .cornerRadius(9999)
                    .frame(width: 44, height: 44)
                }
                .padding(.vertical, 12)
                .padding(.horizontal, 16)
            }
            .frame(maxWidth: .infinity)
            Button(action: {
                // Action here
            }) {
                HStack() {
                    LucideView(icon: .bookMarked) // Lucide: book-marked
                        .frame(width: 20, height: 20)
                }
                .padding(.vertical, 12)
                .padding(.horizontal, 16)
            }
            .frame(maxWidth: .infinity)
        }
        .background(Color(hex: "#FFFFFF"))
        .cornerRadius(AppTheme.borderRadiusPill)
        .overlay(RoundedRectangle(cornerRadius: AppTheme.borderRadiusPill).stroke(AppTheme.borderDivider, lineWidth: 1))
        .frame(height: 80)
    }
    .padding(.horizontal, AppTheme.screenPadding)
    .padding(.bottom, 16)
        }
        .background(AppTheme.backgroundPrimary)
        .ignoresSafeArea(edges: .bottom)
    }
}

#Preview {
    JournalView()
}
