/*
 * AppTheme.kt
 * Drawgle Auto-generated
 */

package com.drawgle.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object AppTheme {
    val BackgroundPrimary = Color(0xFFFFFFFF)
    val BackgroundSecondary = Color(0xFFF3F4F6)
    val SurfaceCard = Color(0xFFFFFFFF)
    val ActionPrimary = Color(0xFF3B82F6)
    val ActionOnPrimary = Color(0xFFFFFFFF)
    val TextHigh = Color(0xFF111827)
    val TextMedium = Color(0xFF4B5563)
    val TextLow = Color(0xFF9CA3AF)
    val BorderDivider = Color(0xFFE5E7EB)
    
    val BorderRadiusApp = 18.dp
    val BorderRadiusPill = 9999.dp
    
    val ScreenPadding = 24.dp
    val SectionGap = 24.dp
    val ElementGap = 16.dp
}

/*
 * JournalScreen.kt
 * Auto-generated by Drawgle
 */

package com.drawgle.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.Alignment
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.* // For Button, Text, Icon
import androidx.compose.foundation.lazy.grid.*
import com.drawgle.theme.AppTheme

@Composable
fun JournalScreen() {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(AppTheme.BackgroundPrimary)
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
        ) {
    Column(
        modifier = Modifier
        .fillMaxWidth()
        .background(AppTheme.BackgroundPrimary),
        horizontalAlignment = Alignment.Start,
    ) {
        Column(
            modifier = Modifier
        .fillMaxWidth()
        .weight(1f)
        .padding(start = 0.dp, top = 16.dp, end = 0.dp, bottom = 96.dp),
            horizontalAlignment = Alignment.Start,
        ) {
            Column(
                modifier = Modifier
        .padding(start = AppTheme.ScreenPadding, top = 0.dp, end = AppTheme.ScreenPadding, bottom = 0.dp),
                horizontalAlignment = Alignment.Start,
            ) {
                Text(
                    text = "Journal",
                    fontSize = 24.sp,
                    color = AppTheme.TextHigh,
                    fontWeight = FontWeight.Bold,
                    modifier = Modifier
                        .padding(top = 0.dp, bottom = AppTheme.SectionGap)
                )
                Column(
                    modifier = Modifier
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(AppTheme.SurfaceCard),
                    horizontalAlignment = Alignment.Start,
                ) {
                    Row(
                        modifier = Modifier,
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween,
                    ) {
                        Row(
                            modifier = Modifier,
                            verticalAlignment = Alignment.CenterVertically,
                        ) {
                            Row(
                                modifier = Modifier
        .width(36.dp)
        .height(36.dp)
        .clip(RoundedCornerShape(9999.dp))
        .background(AppTheme.BackgroundPrimary),
                                verticalAlignment = Alignment.CenterVertically,
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Flame, // Lucide: flame
                                    contentDescription = null,
                                    tint = Color(0xFFFFFFFF),
                                    modifier = Modifier.size(24.dp)
                                )
                            }
                            Column(
                                modifier = Modifier,
                                horizontalAlignment = Alignment.Start,
                            ) {
                                Text(
                                    text = "Calories",
                                    fontSize = 18.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Bold,
                                
                                )
                                Text(
                                    text = "Week Days",
                                    fontSize = 12.sp,
                                    color = AppTheme.TextMedium,
                                    fontWeight = FontWeight.Bold,
                                
                                )
                            }
                        }
                        Button(
                            onClick = { /* Action */ },
                            colors = ButtonDefaults.buttonColors(containerColor = AppTheme.BackgroundPrimary),
                            shape = RoundedCornerShape(9999.dp),
                            modifier = Modifier
                        ) {
                            Row(
                                horizontalArrangement = Arrangement.spacedBy(8.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Calendar, // Lucide: calendar
                                    contentDescription = null,
                                    tint = AppTheme.TextHigh,
                                    modifier = Modifier.size(24.dp)
                                )
                            }
                        }
                    }
                    Column(
                        modifier = Modifier,
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Row(
                            modifier = Modifier
        .clip(RoundedCornerShape(20.dp))
        .background(AppTheme.BackgroundPrimary)
        .padding(start = 0.dp, top = 12.dp, end = 0.dp, bottom = 12.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween,
                        ) {
                            Text(
                                text = "Consumed",
                                fontSize = 16.sp,
                                color = AppTheme.TextMedium,
                                fontWeight = FontWeight.Medium,
                            
                            )
                            Text(
                                text = "00 cal",
                                fontSize = 32.sp,
                                color = AppTheme.TextHigh,
                                fontWeight = FontWeight.Bold,
                            
                            )
                        }
                        Row(
                            modifier = Modifier
        .clip(RoundedCornerShape(20.dp))
        .background(AppTheme.BackgroundPrimary)
        .padding(start = 0.dp, top = 12.dp, end = 0.dp, bottom = 12.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween,
                        ) {
                            Text(
                                text = "Remaining",
                                fontSize = 16.sp,
                                color = AppTheme.TextMedium,
                                fontWeight = FontWeight.Medium,
                            
                            )
                            Text(
                                text = "00 cal",
                                fontSize = 32.sp,
                                color = AppTheme.TextHigh,
                                fontWeight = FontWeight.Bold,
                            
                            )
                        }
                        Box(
                            modifier = Modifier
        .clip(RoundedCornerShape(20.dp))
        .background(AppTheme.BackgroundPrimary)
        .padding(start = 0.dp, top = 12.dp, end = 0.dp, bottom = 12.dp)
                        ) {
                            Column(
                                modifier = Modifier
        .background(Brush.linearGradient(colors = listOf(Color.Transparent, Color(red = 0/255f, green = 0/255f, blue = 0/255f, alpha = 0.03f)), start = Offset(0f, 1f), end = Offset(1f, 0f))),
                                horizontalAlignment = Alignment.Start,
                            ) {
                            }
                            Row(
                                modifier = Modifier.fillMaxSize(),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                Text(
                                    text = "Remaining",
                                    fontSize = 16.sp,
                                    color = AppTheme.TextLow,
                                    fontWeight = FontWeight.Medium,
                                
                                )
                                Text(
                                    text = "00 cal",
                                    fontSize = 32.sp,
                                    color = AppTheme.TextLow,
                                    fontWeight = FontWeight.Bold,
                                
                                )
                            }
                        }
                    }
                    Row(
                        modifier = Modifier,
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween,
                    ) {
                        Column(
                            modifier = Modifier
        .fillMaxWidth()
        .weight(1f),
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Box(
                                modifier = Modifier
        .width(64.dp)
        .height(64.dp)
                            ) {
                                Row(
                                    modifier = Modifier,
                                    verticalAlignment = Alignment.CenterVertically,
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Wheat, // Lucide: wheat
                                        contentDescription = null,
                                        tint = Color(0xFFFFFFFF),
                                        modifier = Modifier.size(24.dp)
                                    )
                                }
                                Column(
                                    modifier = Modifier.fillMaxSize(),
                                    horizontalAlignment = Alignment.Start,
                                ) {
                                    Box(
                                        contentAlignment = Alignment.Center,
                                        modifier = Modifier.size(48.dp)
                                    ) {
                                        CircularProgressIndicator(
                                            progress = 1.00f,
                                            color = AppTheme.BackgroundPrimary,
                                            strokeWidth = 6.dp,
                                            modifier = Modifier.fillMaxSize()
                                        )
                                        CircularProgressIndicator(
                                            progress = 0.00f,
                                            color = Color(0xFFFFFFFF),
                                            strokeWidth = 6.dp,
                                            strokeCap = StrokeCap.Round,
                                            modifier = Modifier.fillMaxSize()
                                        )
                                    }
                                }
                            }
                            Column(
                                modifier = Modifier,
                                horizontalAlignment = Alignment.Start,
                            ) {
                                Text(text = "0/150")
                                Text(
                                    text = "gr",
                                    fontSize = 12.sp,
                                    color = AppTheme.TextLow,
                                
                                )
                            }
                            Text(
                                text = "Power Carbs",
                                fontSize = 12.sp,
                                color = AppTheme.TextMedium,
                                fontWeight = FontWeight.Bold,
                                modifier = Modifier
                                    .padding(top = 2.dp, bottom = 0.dp)
                            )
                        }
                        Column(
                            modifier = Modifier
        .fillMaxWidth()
        .weight(1f),
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Box(
                                modifier = Modifier
        .width(64.dp)
        .height(64.dp)
                            ) {
                                Row(
                                    modifier = Modifier,
                                    verticalAlignment = Alignment.CenterVertically,
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Egg, // Lucide: egg
                                        contentDescription = null,
                                        tint = Color(0xFFFFFFFF),
                                        modifier = Modifier.size(24.dp)
                                    )
                                }
                                Column(
                                    modifier = Modifier.fillMaxSize(),
                                    horizontalAlignment = Alignment.Start,
                                ) {
                                    Box(
                                        contentAlignment = Alignment.Center,
                                        modifier = Modifier.size(48.dp)
                                    ) {
                                        CircularProgressIndicator(
                                            progress = 1.00f,
                                            color = AppTheme.BackgroundPrimary,
                                            strokeWidth = 6.dp,
                                            modifier = Modifier.fillMaxSize()
                                        )
                                        CircularProgressIndicator(
                                            progress = 0.00f,
                                            color = Color(0xFFFFFFFF),
                                            strokeWidth = 6.dp,
                                            strokeCap = StrokeCap.Round,
                                            modifier = Modifier.fillMaxSize()
                                        )
                                    }
                                }
                            }
                            Column(
                                modifier = Modifier,
                                horizontalAlignment = Alignment.Start,
                            ) {
                                Text(text = "0/113")
                                Text(
                                    text = "gr",
                                    fontSize = 12.sp,
                                    color = AppTheme.TextLow,
                                
                                )
                            }
                            Text(
                                text = "Protein Power",
                                fontSize = 12.sp,
                                color = AppTheme.TextMedium,
                                fontWeight = FontWeight.Bold,
                                modifier = Modifier
                                    .padding(top = 2.dp, bottom = 0.dp)
                            )
                        }
                        Column(
                            modifier = Modifier
        .fillMaxWidth()
        .weight(1f),
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Box(
                                modifier = Modifier
        .width(64.dp)
        .height(64.dp)
                            ) {
                                Row(
                                    modifier = Modifier,
                                    verticalAlignment = Alignment.CenterVertically,
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Droplet, // Lucide: droplet
                                        contentDescription = null,
                                        tint = Color(0xFFFFFFFF),
                                        modifier = Modifier.size(24.dp)
                                    )
                                }
                                Column(
                                    modifier = Modifier.fillMaxSize(),
                                    horizontalAlignment = Alignment.Start,
                                ) {
                                    Box(
                                        contentAlignment = Alignment.Center,
                                        modifier = Modifier.size(48.dp)
                                    ) {
                                        CircularProgressIndicator(
                                            progress = 1.00f,
                                            color = AppTheme.BackgroundPrimary,
                                            strokeWidth = 6.dp,
                                            modifier = Modifier.fillMaxSize()
                                        )
                                        CircularProgressIndicator(
                                            progress = 0.00f,
                                            color = Color(0xFFFFFFFF),
                                            strokeWidth = 6.dp,
                                            strokeCap = StrokeCap.Round,
                                            modifier = Modifier.fillMaxSize()
                                        )
                                    }
                                }
                            }
                            Column(
                                modifier = Modifier,
                                horizontalAlignment = Alignment.Start,
                            ) {
                                Text(text = "0/50")
                                Text(
                                    text = "gr",
                                    fontSize = 12.sp,
                                    color = AppTheme.TextLow,
                                
                                )
                            }
                            Text(
                                text = "Healthy Fat",
                                fontSize = 12.sp,
                                color = AppTheme.TextMedium,
                                fontWeight = FontWeight.Bold,
                                modifier = Modifier
                                    .padding(top = 2.dp, bottom = 0.dp)
                            )
                        }
                    }
                }
                LazyVerticalGrid(
                    columns = GridCells.Fixed(2),
                    horizontalArrangement = Arrangement.spacedBy(AppTheme.ElementGap),
                    verticalArrangement = Arrangement.spacedBy(AppTheme.ElementGap),
                    modifier = Modifier.height(280.dp)
                ) {
                    item {
                        Column(
                            modifier = Modifier
        .heightIn(min = 120.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(Color(0xFFFFFFFF)),
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.SpaceBetween,
                        ) {
                            Row(
                                modifier = Modifier,
                                verticalAlignment = Alignment.Top,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                AsyncImage(
                                    model = "https://pub-7c8c3c7444724a39ba3eeb8accbbca4a.r2.dev/visual-assets/b8041495-1552-4079-9c20-80bd656e240f/display_1024.png",
                                    contentDescription = null,
                                    modifier = Modifier
                                        .width(44.dp)
                                        .height(44.dp)
                                        .clip(RoundedCornerShape(9999.dp))
                                )
                                Text(
                                    text = "631 kcal",
                                    fontSize = 14.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Normal,
                                
                                )
                            }
                            Row(
                                modifier = Modifier,
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                Text(
                                    text = "Breakfast",
                                    fontSize = 16.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Medium,
                                
                                )
                                Button(
                                    onClick = { /* Action */ },
                                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                                    shape = RoundedCornerShape(9999.dp),
                                    modifier = Modifier
                                ) {
                                    Row(
                                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Plus, // Lucide: plus
                                            contentDescription = null,
                                            tint = AppTheme.TextHigh,
                                            modifier = Modifier.size(24.dp)
                                        )
                                    }
                                }
                            }
                        }
                    }
                    item {
                        Column(
                            modifier = Modifier
        .heightIn(min = 120.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(Color(0xFFFFFFFF)),
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.SpaceBetween,
                        ) {
                            Row(
                                modifier = Modifier,
                                verticalAlignment = Alignment.Top,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                Row(
                                    modifier = Modifier
        .width(44.dp)
        .height(44.dp)
        .clip(RoundedCornerShape(9999.dp)),
                                    verticalAlignment = Alignment.CenterVertically,
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Salad, // Lucide: salad
                                        contentDescription = null,
                                        tint = AppTheme.TextMedium,
                                        modifier = Modifier.size(24.dp)
                                    )
                                }
                                Text(
                                    text = "486 kcal",
                                    fontSize = 14.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Normal,
                                
                                )
                            }
                            Row(
                                modifier = Modifier,
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                Text(
                                    text = "Lunch",
                                    fontSize = 16.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Medium,
                                
                                )
                                Button(
                                    onClick = { /* Action */ },
                                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                                    shape = RoundedCornerShape(9999.dp),
                                    modifier = Modifier
                                ) {
                                    Row(
                                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Plus, // Lucide: plus
                                            contentDescription = null,
                                            tint = AppTheme.TextHigh,
                                            modifier = Modifier.size(24.dp)
                                        )
                                    }
                                }
                            }
                        }
                    }
                    item {
                        Column(
                            modifier = Modifier
        .heightIn(min = 120.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(Color(0xFFFFFFFF)),
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.SpaceBetween,
                        ) {
                            Row(
                                modifier = Modifier,
                                verticalAlignment = Alignment.Top,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                Row(
                                    modifier = Modifier
        .width(44.dp)
        .height(44.dp)
        .clip(RoundedCornerShape(9999.dp)),
                                    verticalAlignment = Alignment.CenterVertically,
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Soup, // Lucide: soup
                                        contentDescription = null,
                                        tint = AppTheme.TextMedium,
                                        modifier = Modifier.size(24.dp)
                                    )
                                }
                                Text(
                                    text = "359 kcal",
                                    fontSize = 14.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Normal,
                                
                                )
                            }
                            Row(
                                modifier = Modifier,
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                Text(
                                    text = "Dinner",
                                    fontSize = 16.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Medium,
                                
                                )
                                Button(
                                    onClick = { /* Action */ },
                                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                                    shape = RoundedCornerShape(9999.dp),
                                    modifier = Modifier
                                ) {
                                    Row(
                                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Plus, // Lucide: plus
                                            contentDescription = null,
                                            tint = AppTheme.TextHigh,
                                            modifier = Modifier.size(24.dp)
                                        )
                                    }
                                }
                            }
                        }
                    }
                    item {
                        Column(
                            modifier = Modifier
        .heightIn(min = 120.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(Color(0xFFFFE0B2)),
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.SpaceBetween,
                        ) {
                            Row(
                                modifier = Modifier,
                                verticalAlignment = Alignment.Top,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                Row(
                                    modifier = Modifier
        .width(44.dp)
        .height(44.dp)
        .clip(RoundedCornerShape(9999.dp)),
                                    verticalAlignment = Alignment.CenterVertically,
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Cookie, // Lucide: cookie
                                        contentDescription = null,
                                        tint = AppTheme.TextMedium,
                                        modifier = Modifier.size(24.dp)
                                    )
                                }
                                Text(
                                    text = "193 kcal",
                                    fontSize = 14.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Normal,
                                
                                )
                            }
                            Row(
                                modifier = Modifier,
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                            ) {
                                Text(
                                    text = "Snack",
                                    fontSize = 16.sp,
                                    color = AppTheme.TextHigh,
                                    fontWeight = FontWeight.Medium,
                                
                                )
                                Button(
                                    onClick = { /* Action */ },
                                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                                    shape = RoundedCornerShape(9999.dp),
                                    modifier = Modifier
                                ) {
                                    Row(
                                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Plus, // Lucide: plus
                                            contentDescription = null,
                                            tint = AppTheme.TextHigh,
                                            modifier = Modifier.size(24.dp)
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
        }
    Column(
        modifier = Modifier
        .padding(start = AppTheme.ScreenPadding, top = 0.dp, end = AppTheme.ScreenPadding, bottom = 16.dp)
        .align(Alignment.BottomCenter)
        .fillMaxWidth(),
        horizontalAlignment = Alignment.Start,
    ) {
        Row(
            modifier = Modifier
        .height(80.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusPill))
        .background(Color(0xFFFFFFFF))
        .border(1.dp, AppTheme.BorderDivider, RoundedCornerShape(AppTheme.BorderRadiusPill)),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Button(
                onClick = { /* Action */ },
                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier
            ) {
                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Icon(
                        imageVector = Icons.Default.ChefHat, // Lucide: chef-hat
                        contentDescription = null,
                        tint = AppTheme.TextLow,
                        modifier = Modifier.size(24.dp)
                    )
                }
            }
            Button(
                onClick = { /* Action */ },
                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier
            ) {
                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Icon(
                        imageVector = Icons.Default.CalendarDays, // Lucide: calendar-days
                        contentDescription = null,
                        tint = AppTheme.TextLow,
                        modifier = Modifier.size(24.dp)
                    )
                }
            }
            Button(
                onClick = { /* Action */ },
                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier
            ) {
                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Icon(
                        imageVector = Icons.Default.Sparkles, // Lucide: sparkles
                        contentDescription = null,
                        tint = AppTheme.TextLow,
                        modifier = Modifier.size(24.dp)
                    )
                }
            }
            Button(
                onClick = { /* Action */ },
                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier
            ) {
                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Row(
                        modifier = Modifier
        .width(44.dp)
        .height(44.dp)
        .clip(RoundedCornerShape(9999.dp))
        .background(AppTheme.ActionPrimary),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Icon(
                            imageVector = Icons.Default.BookOpen, // Lucide: book-open
                            contentDescription = null,
                            tint = AppTheme.ActionOnPrimary,
                            modifier = Modifier.size(24.dp)
                        )
                    }
                }
            }
            Button(
                onClick = { /* Action */ },
                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier
            ) {
                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Icon(
                        imageVector = Icons.Default.BookMarked, // Lucide: book-marked
                        contentDescription = null,
                        tint = AppTheme.TextLow,
                        modifier = Modifier.size(24.dp)
                    )
                }
            }
        }
    }
    }
}
