//
// app_theme.dart
// Drawgle Auto-generated
//

import 'package:flutter/material.dart';

class AppTheme {
  static const Color backgroundPrimary = Color(0xFFFFFFFF);
  static const Color backgroundSecondary = Color(0xFFF3F4F6);
  static const Color surfaceCard = Color(0xFFFFFFFF);
  static const Color actionPrimary = Color(0xFF3B82F6);
  static const Color actionOnPrimary = Color(0xFFFFFFFF);
  static const Color textHigh = Color(0xFF111827);
  static const Color textMedium = Color(0xFF4B5563);
  static const Color textLow = Color(0xFF9CA3AF);
  static const Color borderDivider = Color(0xFFE5E7EB);
  
  static const double borderRadiusApp = 18;
  static const double borderRadiusPill = 9999.0;
  
  static const double screenPadding = 24;
  static const double sectionGap = 24;
  static const double elementGap = 16;
}

//
// journal_screen.dart
// Auto-generated by Drawgle
//

import 'package:flutter/material.dart';
import 'app_theme.dart';

class JournalScreen extends StatelessWidget {
  const JournalScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.backgroundPrimary,
      body: SafeArea(
        child: Stack(
          children: [
            SingleChildScrollView(
              child: Container(
    constraints: BoxConstraints(minHeight: 100.0),
    child: Column(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    mainAxisAlignment: MainAxisAlignment.start,
    children: [
    Container(
      width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
      decoration: BoxDecoration(
      color: AppTheme.backgroundPrimary
    ),
      child: Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      mainAxisAlignment: MainAxisAlignment.start,
      children: [
      Container(
        width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
        padding: EdgeInsets.only(left: 24.0, top: 20.0, right: 24.0, bottom: 8.0),
        child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
        Text(
          '9:41',
          style: TextStyle(
            fontSize: 14.0,
            color: AppTheme.textHigh,
            fontWeight: FontWeight.w500
    ),
        ),
        Container(
          constraints: BoxConstraints(minHeight: 100.0),
          child: Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
          Icon(Icons.signal, size: 24.0, color: Colors.transparent),
          SizedBox(width: 6.0),
          Icon(Icons.wifi, size: 24.0, color: Colors.transparent),
          SizedBox(width: 6.0),
          Icon(Icons.battery_full, size: 24.0, color: Colors.transparent)
          ]
    ),
        )
        ]
    ),
      ),
      Container(
        width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
        padding: EdgeInsets.only(left: AppTheme.screenPadding, top: 12.0, right: AppTheme.screenPadding, bottom: 8.0),
        child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
        Text(
          'Journal',
          style: Theme.of(context).textTheme.headlineLarge?.copyWith(
            color: AppTheme.textHigh,
            fontWeight: FontWeight.w800
    ),
        ),
        SizedBox(
          width: 44.0,
          height: 44.0,
          child: ElevatedButton(
          onPressed: () {},
          style: ElevatedButton.styleFrom(
            backgroundColor: Color(0xFFF5F5FA),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(9999.0)
    ),
            elevation: 0.0,
            padding: EdgeInsets.zero,
            minimumSize: Size.zero,
            tapTargetSize: MaterialTapTargetSize.shrinkWrap
    ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.more_horiz, size: 24.0, color: AppTheme.textHigh)
            ]
    )),
)
        ]
    ),
      ),
      Container(
        width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
        padding: EdgeInsets.only(left: AppTheme.screenPadding, top: 8.0, right: AppTheme.screenPadding, bottom: 120.0),
        child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
        Container(
          width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
          padding: EdgeInsets.only(left: 20.0, top: 20.0, right: 20.0, bottom: 20.0),
          decoration: BoxDecoration(
      color: AppTheme.surfaceCard,
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp),
      boxShadow: [
        BoxShadow(
          color: Color(0x0A000000),
          blurRadius: 30.0,
          offset: Offset(0.0, 10.0)
    ),
      ]
    ),
          child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
          Container(
            width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
            child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
            Container(
              constraints: BoxConstraints(minHeight: 100.0),
              child: Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
              Container(
                width: 40.0,
    height: 40.0,
    constraints: BoxConstraints(minHeight: 100.0),
                decoration: BoxDecoration(
      color: Color.fromRGBO(255, 214, 0, 0.18),
      borderRadius: BorderRadius.circular(9999.0)
    ),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                Text(
                  '🔥',
                  style: TextStyle(
                    fontSize: 20.0
    ),
                )
                ]
    ),
              ),
              SizedBox(width: 12.0),
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                Text(
                  'Calories',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.bold
    ),
                ),
                Text(
                  'Week Days',
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: AppTheme.textMedium,
                    fontWeight: FontWeight.normal
    ),
                )
                ]
    ),
              )
              ]
    ),
            ),
            SizedBox(
              width: 44.0,
              height: 44.0,
              child: ElevatedButton(
              onPressed: () {},
              style: ElevatedButton.styleFrom(
                backgroundColor: Color(0xFFF5F5FA),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(9999.0)
    ),
                elevation: 0.0,
                padding: EdgeInsets.zero,
                minimumSize: Size.zero,
                tapTargetSize: MaterialTapTargetSize.shrinkWrap
    ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.calendar_today, size: 24.0, color: AppTheme.textHigh)
                ]
    )),
)
            ]
    ),
          ),
          SizedBox(height: 16.0),
          Container(
            width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
            child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
            Container(
              width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
              padding: EdgeInsets.only(left: 16.0, top: 12.0, right: 16.0, bottom: 12.0),
              decoration: BoxDecoration(
      color: AppTheme.backgroundPrimary,
      borderRadius: BorderRadius.circular(18.0)
    ),
              child: Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
              Text(
                'Consumed',
                style: TextStyle(
                  fontSize: 14.0,
                  color: AppTheme.textMedium,
                  fontWeight: FontWeight.w500
    ),
              ),
              Text(
                '00 cal',
                style: TextStyle(
                  fontSize: 18.0,
                  color: AppTheme.textHigh,
                  fontWeight: FontWeight.w600
    ),
              )
              ]
    ),
            ),
            SizedBox(height: 10.0),
            Container(
              width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
              padding: EdgeInsets.only(left: 16.0, top: 12.0, right: 16.0, bottom: 12.0),
              decoration: BoxDecoration(
      color: AppTheme.backgroundPrimary,
      borderRadius: BorderRadius.circular(18.0)
    ),
              child: Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
              Text(
                'Remaining',
                style: TextStyle(
                  fontSize: 14.0,
                  color: AppTheme.textMedium,
                  fontWeight: FontWeight.w500
    ),
              ),
              Text(
                '00 cal',
                style: TextStyle(
                  fontSize: 18.0,
                  color: AppTheme.textHigh,
                  fontWeight: FontWeight.w600
    ),
              )
              ]
    ),
            ),
            SizedBox(height: 10.0),
            Container(
              width: double.infinity,
    constraints: BoxConstraints(minHeight: 100.0),
              padding: EdgeInsets.only(left: 16.0, top: 12.0, right: 16.0, bottom: 12.0),
              decoration: BoxDecoration(
      gradient: LinearGradient(
        begin: Alignment.bottomLeft,
        end: Alignment.topRight,
        colors: [Color(0xFFEDEDF3), Color(0xFFE2E2EA)]
    ),
      borderRadius: BorderRadius.circular(18.0)
    ),
              child: Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
              Text(
                'Remaining',
                style: TextStyle(
                  fontSize: 14.0,
                  color: AppTheme.textLow,
                  fontWeight: FontWeight.w500
    ),
              ),
              Text(
                '00 cal',
                style: TextStyle(
                  fontSize: 18.0,
                  color: AppTheme.textLow,
                  fontWeight: FontWeight.w600
    ),
              )
              ]
    ),
            )
            ]
    ),
          ),
          SizedBox(height: 16.0),
          Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
              Expanded(
                child: Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                Stack(
                  children: [
                  Positioned.fill(
                    child: Container(
                    constraints: BoxConstraints(minHeight: 100.0),
                    child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                    Container(
                      constraints: BoxConstraints(minHeight: 100.0),
                      child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                      Text(
                        '0',
                        style: TextStyle(
                          fontWeight: FontWeight.bold
    ),
                      ),
                      Text(
                        '/150',
                        style: TextStyle(
                          fontSize: 10.0,
                          color: AppTheme.textMedium
    ),
                      )
                      ]
    ),
                    ),
                    Text(
                      'gr',
                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        color: AppTheme.textLow,
                        fontWeight: FontWeight.normal
    ),
                    )
                    ]
    ),
                  )
    ),
                Container(
                  width: 72.0,
    height: 72.0,
    constraints: BoxConstraints(minHeight: 100.0),
                  child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  Stack(
                    alignment: Alignment.center,
                    children: [
                      SizedBox(
                        width: 48.0,
                        height: 48.0,
                        child: CircularProgressIndicator(
                          value: 1.00,
                          valueColor: AlwaysStoppedAnimation<Color>(AppTheme.borderDivider),
                          strokeWidth: 8.0
    ),
                      ),
                      SizedBox(
                        width: 48.0,
                        height: 48.0,
                        child: CircularProgressIndicator(
                          value: 0.00,
                          valueColor: AlwaysStoppedAnimation<Color>(Color(0xFFFF9A1F)),
                          strokeWidth: 8.0,
                          strokeCap: StrokeCap.round
    ),
                      ),
                    ],
                  )
                  ]
    ),
                ),
                  ]
    ),
                SizedBox(height: 6.0),
                Container(
                  constraints: BoxConstraints(minHeight: 100.0),
                  child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                  Text(
                    'Power',
                    style: TextStyle(
                      fontSize: 14.0,
                      color: AppTheme.textHigh,
                      fontWeight: FontWeight.w500
    ),
                  ),
                  Text(
                    'Carbs',
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      color: AppTheme.textMedium,
                      fontWeight: FontWeight.normal
    ),
                  )
                  ]
    ),
                )
                ]
    ),
              )
    ),
              SizedBox(width: 12.0),
              Expanded(
                child: Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                Stack(
                  children: [
                  Positioned.fill(
                    child: Container(
                    constraints: BoxConstraints(minHeight: 100.0),
                    child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                    Container(
                      constraints: BoxConstraints(minHeight: 100.0),
                      child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                      Text(
                        '0',
                        style: TextStyle(
                          fontWeight: FontWeight.bold
    ),
                      ),
                      Text(
                        '/113',
                        style: TextStyle(
                          fontSize: 10.0,
                          color: AppTheme.textMedium
    ),
                      )
                      ]
    ),
                    ),
                    Text(
                      'gr',
                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        color: AppTheme.textLow,
                        fontWeight: FontWeight.normal
    ),
                    )
                    ]
    ),
                  )
    ),
                Container(
                  width: 72.0,
    height: 72.0,
    constraints: BoxConstraints(minHeight: 100.0),
                  child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  Stack(
                    alignment: Alignment.center,
                    children: [
                      SizedBox(
                        width: 48.0,
                        height: 48.0,
                        child: CircularProgressIndicator(
                          value: 1.00,
                          valueColor: AlwaysStoppedAnimation<Color>(AppTheme.borderDivider),
                          strokeWidth: 8.0
    ),
                      ),
                      SizedBox(
                        width: 48.0,
                        height: 48.0,
                        child: CircularProgressIndicator(
                          value: 0.00,
                          valueColor: AlwaysStoppedAnimation<Color>(Color(0xFFFF9A1F)),
                          strokeWidth: 8.0,
                          strokeCap: StrokeCap.round
    ),
                      ),
                    ],
                  )
                  ]
    ),
                ),
                  ]
    ),
                SizedBox(height: 6.0),
                Container(
                  constraints: BoxConstraints(minHeight: 100.0),
                  child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                  Text(
                    'Protein',
                    style: TextStyle(
                      fontSize: 14.0,
                      color: AppTheme.textHigh,
                      fontWeight: FontWeight.w500
    ),
                  ),
                  Text(
                    'Power',
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      color: AppTheme.textMedium,
                      fontWeight: FontWeight.normal
    ),
                  )
                  ]
    ),
                )
                ]
    ),
              )
    ),
              SizedBox(width: 12.0),
              Expanded(
                child: Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                Stack(
                  children: [
                  Positioned.fill(
                    child: Container(
                    constraints: BoxConstraints(minHeight: 100.0),
                    child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                    Container(
                      constraints: BoxConstraints(minHeight: 100.0),
                      child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                      Text(
                        '0',
                        style: TextStyle(
                          fontWeight: FontWeight.bold
    ),
                      ),
                      Text(
                        '/50',
                        style: TextStyle(
                          fontSize: 10.0,
                          color: AppTheme.textMedium
    ),
                      )
                      ]
    ),
                    ),
                    Text(
                      'gr',
                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        color: AppTheme.textLow,
                        fontWeight: FontWeight.normal
    ),
                    )
                    ]
    ),
                  )
    ),
                Container(
                  width: 72.0,
    height: 72.0,
    constraints: BoxConstraints(minHeight: 100.0),
                  child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  Stack(
                    alignment: Alignment.center,
                    children: [
                      SizedBox(
                        width: 48.0,
                        height: 48.0,
                        child: CircularProgressIndicator(
                          value: 1.00,
                          valueColor: AlwaysStoppedAnimation<Color>(AppTheme.borderDivider),
                          strokeWidth: 8.0
    ),
                      ),
                      SizedBox(
                        width: 48.0,
                        height: 48.0,
                        child: CircularProgressIndicator(
                          value: 0.00,
                          valueColor: AlwaysStoppedAnimation<Color>(Color(0xFFFF9A1F)),
                          strokeWidth: 8.0,
                          strokeCap: StrokeCap.round
    ),
                      ),
                    ],
                  )
                  ]
    ),
                ),
                  ]
    ),
                SizedBox(height: 6.0),
                Container(
                  constraints: BoxConstraints(minHeight: 100.0),
                  child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                  Text(
                    'Healthy',
                    style: TextStyle(
                      fontSize: 14.0,
                      color: AppTheme.textHigh,
                      fontWeight: FontWeight.w500
    ),
                  ),
                  Text(
                    'Fat',
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      color: AppTheme.textMedium,
                      fontWeight: FontWeight.normal
    ),
                  )
                  ]
    ),
                )
                ]
    ),
              )
    ),
              ]
    ),
            ],
          )
          ]
    ),
        ),
        SizedBox(height: AppTheme.sectionGap),
        Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
            Expanded(
              child: Container(
              constraints: BoxConstraints(minHeight: 100.0),
              padding: EdgeInsets.only(left: 16.0, top: 16.0, right: 16.0, bottom: 16.0),
              decoration: BoxDecoration(
      color: Color(0xFFD8D2FF),
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp)
    ),
              child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Container(
                  width: 56.0,
    height: 56.0,
    constraints: BoxConstraints(minHeight: 100.0),
                  decoration: BoxDecoration(
      color: Color.fromRGBO(255, 255, 255, 0.55),
      borderRadius: BorderRadius.circular(9999.0)
    ),
                  child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(0.0),
                    child: Image.network(
                      'https://pub-7c8c3c7444724a39ba3eeb8accbbca4a.r2.dev/visual-assets/b8041495-1552-4079-9c20-80bd656e240f/display_1024.png',
                      width: double.infinity,
                      height: double.infinity,
                      fit: BoxFit.contain,
                  )
                  ]
    ),
                ),
                Text(
                  '631 kcal',
                  style: TextStyle(
                    fontSize: 18.0,
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.w600
    ),
                )
                ]
    ),
              ),
              SizedBox(height: 12.0),
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Text(
                  'Breakfast',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.bold
    ),
                ),
                SizedBox(
                  width: 36.0,
                  height: 36.0,
                  child: ElevatedButton(
                  onPressed: () {},
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(0xFFF5F5FA),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(9999.0)
    ),
                    elevation: 4.0,
                    shadowColor: Color(0x0A000000),
                    padding: EdgeInsets.zero,
                    minimumSize: Size.zero,
                    tapTargetSize: MaterialTapTargetSize.shrinkWrap
    ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.add, size: 24.0, color: AppTheme.textHigh)
                    ]
    )),
)
                ]
    ),
              )
              ]
    ),
            )
    ),
            SizedBox(width: 12.0),
            Expanded(
              child: Container(
              constraints: BoxConstraints(minHeight: 100.0),
              padding: EdgeInsets.only(left: 16.0, top: 16.0, right: 16.0, bottom: 16.0),
              decoration: BoxDecoration(
      color: Color(0xFFFFE680),
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp)
    ),
              child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Container(
                  width: 56.0,
    height: 56.0,
    constraints: BoxConstraints(minHeight: 100.0),
                  decoration: BoxDecoration(
      color: Color.fromRGBO(255, 255, 255, 0.55),
      borderRadius: BorderRadius.circular(9999.0)
    ),
                  child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  Icon(Icons.spa, size: 24.0, color: Color(0xFF7A6B2E))
                  ]
    ),
                ),
                Text(
                  '486 kcal',
                  style: TextStyle(
                    fontSize: 18.0,
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.w600
    ),
                )
                ]
    ),
              ),
              SizedBox(height: 12.0),
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Text(
                  'Lunch',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.bold
    ),
                ),
                SizedBox(
                  width: 36.0,
                  height: 36.0,
                  child: ElevatedButton(
                  onPressed: () {},
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(0xFFF5F5FA),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(9999.0)
    ),
                    elevation: 4.0,
                    shadowColor: Color(0x0A000000),
                    padding: EdgeInsets.zero,
                    minimumSize: Size.zero,
                    tapTargetSize: MaterialTapTargetSize.shrinkWrap
    ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.add, size: 24.0, color: AppTheme.textHigh)
                    ]
    )),
)
                ]
    ),
              )
              ]
    ),
            )
    ),
            ]
    ),
          SizedBox(height: 12.0),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
            Expanded(
              child: Container(
              constraints: BoxConstraints(minHeight: 100.0),
              padding: EdgeInsets.only(left: 16.0, top: 16.0, right: 16.0, bottom: 16.0),
              decoration: BoxDecoration(
      color: Color(0xFFB6F1C8),
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp)
    ),
              child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Container(
                  width: 56.0,
    height: 56.0,
    constraints: BoxConstraints(minHeight: 100.0),
                  decoration: BoxDecoration(
      color: Color.fromRGBO(255, 255, 255, 0.55),
      borderRadius: BorderRadius.circular(9999.0)
    ),
                  child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  Icon(Icons.restaurant, size: 24.0, color: Color(0xFF2F6A47))
                  ]
    ),
                ),
                Text(
                  '359 kcal',
                  style: TextStyle(
                    fontSize: 18.0,
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.w600
    ),
                )
                ]
    ),
              ),
              SizedBox(height: 12.0),
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Text(
                  'Dinner',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.bold
    ),
                ),
                SizedBox(
                  width: 36.0,
                  height: 36.0,
                  child: ElevatedButton(
                  onPressed: () {},
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(0xFFF5F5FA),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(9999.0)
    ),
                    elevation: 4.0,
                    shadowColor: Color(0x0A000000),
                    padding: EdgeInsets.zero,
                    minimumSize: Size.zero,
                    tapTargetSize: MaterialTapTargetSize.shrinkWrap
    ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.add, size: 24.0, color: AppTheme.textHigh)
                    ]
    )),
)
                ]
    ),
              )
              ]
    ),
            )
    ),
            SizedBox(width: 12.0),
            Expanded(
              child: Container(
              constraints: BoxConstraints(minHeight: 100.0),
              padding: EdgeInsets.only(left: 16.0, top: 16.0, right: 16.0, bottom: 16.0),
              decoration: BoxDecoration(
      color: Color(0xFFFFCBA4),
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp)
    ),
              child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Container(
                  width: 56.0,
    height: 56.0,
    constraints: BoxConstraints(minHeight: 100.0),
                  decoration: BoxDecoration(
      color: Color.fromRGBO(255, 255, 255, 0.55),
      borderRadius: BorderRadius.circular(9999.0)
    ),
                  child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  Icon(Icons.cookie, size: 24.0, color: Color(0xFF7A4521))
                  ]
    ),
                ),
                Text(
                  '193 kcal',
                  style: TextStyle(
                    fontSize: 18.0,
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.w600
    ),
                )
                ]
    ),
              ),
              SizedBox(height: 12.0),
              Container(
                constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Text(
                  'Snack',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    color: AppTheme.textHigh,
                    fontWeight: FontWeight.bold
    ),
                ),
                SizedBox(
                  width: 36.0,
                  height: 36.0,
                  child: ElevatedButton(
                  onPressed: () {},
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(0xFFF5F5FA),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(9999.0)
    ),
                    elevation: 4.0,
                    shadowColor: Color(0x0A000000),
                    padding: EdgeInsets.zero,
                    minimumSize: Size.zero,
                    tapTargetSize: MaterialTapTargetSize.shrinkWrap
    ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.add, size: 24.0, color: AppTheme.textHigh)
                    ]
    )),
)
                ]
    ),
              )
              ]
    ),
            )
    ),
            ]
    ),
          ],
        )
        ]
    ),
      )
      ]
    ),
    ),
    Container(
      constraints: BoxConstraints(minHeight: 100.0),
    )
    ]
    ),
  ),
            ),
  Align(
    alignment: Alignment.bottomCenter,
    child: Container(
    constraints: BoxConstraints(minHeight: 100.0, maxWidth: 356.0),
    padding: EdgeInsets.only(left: 8.0, top: 8.0, right: 8.0, bottom: 8.0),
    decoration: BoxDecoration(
      borderRadius: BorderRadius.circular(999.0),
      border: Border.all(color: Color.fromRGBO(0, 0, 0, 0.05), width: 1.0)
    ),
    child: Row(
    crossAxisAlignment: CrossAxisAlignment.center,
    mainAxisAlignment: MainAxisAlignment.spaceAround,
    children: [
    Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
      Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
        Expanded(
          child: SizedBox(
          width: double.infinity,
          height: 48.0,
          child: ElevatedButton(
          onPressed: () {},
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.transparent,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(999.0)
    ),
            elevation: 0.0,
            padding: EdgeInsets.zero,
            minimumSize: Size.zero,
            tapTargetSize: MaterialTapTargetSize.shrinkWrap
    ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                width: 18.0,
    height: 18.0,
    constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                Icon(Icons.home, size: 24.0, color: Colors.transparent)
                ]
    ),
              ),
              SizedBox(width: 3.0),
              Text(
                'Meal Plan',
                style: Theme.of(context).textTheme.labelMedium,
              )
            ]
    ),
        )
    ),
        ),
        SizedBox(width: 4.0),
        Expanded(
          child: SizedBox(
          width: double.infinity,
          height: 48.0,
          child: ElevatedButton(
          onPressed: () {},
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.transparent,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(999.0)
    ),
            elevation: 0.0,
            padding: EdgeInsets.zero,
            minimumSize: Size.zero,
            tapTargetSize: MaterialTapTargetSize.shrinkWrap
    ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                width: 18.0,
    height: 18.0,
    constraints: BoxConstraints(minHeight: 100.0),
                child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                Icon(Icons.search, size: 24.0, color: Colors.transparent)
                ]
    ),
              ),
              SizedBox(width: 3.0),
              Text(
                'Journal',
                style: Theme.of(context).textTheme.labelMedium,
              )
            ]
    ),
        )
    ),
        ),
        ]
    ),
      ],
    )
    ]
    )),
)
          ],
        ),
      ),
    );
  }
}
