/*
 * AppTheme.kt
 * Drawgle Auto-generated
 */

package com.drawgle.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object AppTheme {
    val BackgroundPrimary = Color(0xFFFFFFFF)
    val BackgroundSecondary = Color(0xFFF3F4F6)
    val SurfaceCard = Color(0xFFFFFFFF)
    val ActionPrimary = Color(0xFF3B82F6)
    val ActionOnPrimary = Color(0xFFFFFFFF)
    val TextHigh = Color(0xFF111827)
    val TextMedium = Color(0xFF4B5563)
    val TextLow = Color(0xFF9CA3AF)
    val BorderDivider = Color(0xFFE5E7EB)
    
    val BorderRadiusApp = 18.dp
    val BorderRadiusPill = 9999.dp
    
    val ScreenPadding = 24.dp
    val SectionGap = 24.dp
    val ElementGap = 16.dp
}

/*
 * JournalScreen.kt
 * Auto-generated by Drawgle
 */

package com.drawgle.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.Alignment
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.* // For Button, Text, Icon
import androidx.compose.foundation.lazy.grid.*
import com.drawgle.theme.AppTheme

@Composable
fun JournalScreen() {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(AppTheme.BackgroundPrimary)
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
        ) {
    Column(
        modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
        horizontalAlignment = Alignment.Start,
        verticalArrangement = Arrangement.Top
    ) {
        Column(
            modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .background(AppTheme.BackgroundPrimary),
            horizontalAlignment = Alignment.Start,
            verticalArrangement = Arrangement.Top
        ) {
            Row(
                modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA))
        .padding(start = 24.dp, top = 20.dp, end = 24.dp, bottom = 8.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text(
                    text = "9:41",
                    fontSize = 14.sp,
                    color = AppTheme.TextHigh,
                    fontWeight = FontWeight.Medium,
                    modifier = Modifier
                )
                Row(
                    modifier = Modifier
        .heightIn(min = 100.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.Signal, // Lucide: signal
                        contentDescription = null,
                        tint = Color.Transparent,
                        modifier = Modifier
        .size(24.dp)
                    )
                    Icon(
                        imageVector = Icons.Default.Wifi, // Lucide: wifi
                        contentDescription = null,
                        tint = Color.Transparent,
                        modifier = Modifier
        .size(24.dp)
                    )
                    Icon(
                        imageVector = Icons.Default.BatteryFull, // Lucide: battery-full
                        contentDescription = null,
                        tint = Color.Transparent,
                        modifier = Modifier
        .size(24.dp)
                    )
                }
            }
            Row(
                modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA))
        .padding(start = AppTheme.ScreenPadding, top = 12.dp, end = AppTheme.ScreenPadding, bottom = 8.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text(
                    text = "Journal",
                    style = MaterialTheme.typography.headlineLarge.copy(color = AppTheme.TextHigh),
                    modifier = Modifier
                )
                Button(
                    onClick = { /* Action */ },
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF5F5FA)),
                    shape = RoundedCornerShape(9999.dp),
                    contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                    modifier = Modifier
                ) {
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = Icons.Default.MoreHorizontal, // Lucide: more-horizontal
                            contentDescription = null,
                            tint = AppTheme.TextHigh,
                            modifier = Modifier
        .size(24.dp)
                        )
                    }
                }
            }
            Column(
                modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA))
        .padding(start = AppTheme.ScreenPadding, top = 8.dp, end = AppTheme.ScreenPadding, bottom = 120.dp),
                horizontalAlignment = Alignment.Start,
                verticalArrangement = Arrangement.spacedBy(AppTheme.SectionGap)
            ) {
                Column(
                    modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .shadow(elevation = 8.dp, shape = RoundedCornerShape(AppTheme.BorderRadiusApp))
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(AppTheme.SurfaceCard)
        .padding(start = 20.dp, top = 20.dp, end = 20.dp, bottom = 20.dp),
                    horizontalAlignment = Alignment.Start,
                    verticalArrangement = Arrangement.spacedBy(16.dp)
                ) {
                    Row(
                        modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Row(
                            modifier = Modifier
        .heightIn(min = 100.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(12.dp)
                        ) {
                            Row(
                                modifier = Modifier
        .width(40.dp)
        .height(40.dp)
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(9999.dp))
        .background(Color(red = 255/255f, green = 214/255f, blue = 0/255f, alpha = 0.18f)),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.Start
                            ) {
                                Text(
                                    text = "🔥",
                                    fontSize = 20.sp,
                                    modifier = Modifier
                                )
                            }
                            Column(
                                modifier = Modifier
        .heightIn(min = 100.dp),
                                horizontalAlignment = Alignment.Start,
                                verticalArrangement = Arrangement.Top
                            ) {
                                Text(
                                    text = "Calories",
                                    style = MaterialTheme.typography.titleLarge.copy(color = AppTheme.TextHigh),
                                    modifier = Modifier
                                )
                                Text(
                                    text = "Week Days",
                                    style = MaterialTheme.typography.bodyMedium.copy(color = AppTheme.TextMedium),
                                    modifier = Modifier
                                )
                            }
                        }
                        Button(
                            onClick = { /* Action */ },
                            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF5F5FA)),
                            shape = RoundedCornerShape(9999.dp),
                            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                            modifier = Modifier
                        ) {
                            Row(
                                horizontalArrangement = Arrangement.spacedBy(8.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Calendar, // Lucide: calendar
                                    contentDescription = null,
                                    tint = AppTheme.TextHigh,
                                    modifier = Modifier
        .size(24.dp)
                                )
                            }
                        }
                    }
                    Column(
                        modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                        horizontalAlignment = Alignment.Start,
                        verticalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        Row(
                            modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(18.dp))
        .background(AppTheme.BackgroundPrimary)
        .padding(start = 16.dp, top = 12.dp, end = 16.dp, bottom = 12.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Text(
                                text = "Consumed",
                                fontSize = 14.sp,
                                color = AppTheme.TextMedium,
                                fontWeight = FontWeight.Medium,
                                modifier = Modifier
                            )
                            Text(
                                text = "00 cal",
                                fontSize = 18.sp,
                                color = AppTheme.TextHigh,
                                fontWeight = FontWeight.Medium,
                                modifier = Modifier
                            )
                        }
                        Row(
                            modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(18.dp))
        .background(AppTheme.BackgroundPrimary)
        .padding(start = 16.dp, top = 12.dp, end = 16.dp, bottom = 12.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Text(
                                text = "Remaining",
                                fontSize = 14.sp,
                                color = AppTheme.TextMedium,
                                fontWeight = FontWeight.Medium,
                                modifier = Modifier
                            )
                            Text(
                                text = "00 cal",
                                fontSize = 18.sp,
                                color = AppTheme.TextHigh,
                                fontWeight = FontWeight.Medium,
                                modifier = Modifier
                            )
                        }
                        Row(
                            modifier = Modifier
        .fillMaxWidth()
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(18.dp))
        .background(Brush.linearGradient(colors = listOf(Color(0xFFEDEDF3), Color(0xFFE2E2EA)), start = Offset(0f, 1f), end = Offset(1f, 0f)))
        .padding(start = 16.dp, top = 12.dp, end = 16.dp, bottom = 12.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Text(
                                text = "Remaining",
                                fontSize = 14.sp,
                                color = AppTheme.TextLow,
                                fontWeight = FontWeight.Medium,
                                modifier = Modifier
                            )
                            Text(
                                text = "00 cal",
                                fontSize = 18.sp,
                                color = AppTheme.TextLow,
                                fontWeight = FontWeight.Medium,
                                modifier = Modifier
                            )
                        }
                    }
                    Column(
                        modifier = Modifier
        .fillMaxWidth()
        .background(Color(0xFFF5F5FA)),
                        verticalArrangement = Arrangement.spacedBy(12.dp)
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.spacedBy(12.dp)
                        ) {
                            Box(modifier = Modifier.weight(1f)) {
                                Column(
                                    modifier = Modifier
        .heightIn(min = 100.dp),
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    Box(
                                        modifier = Modifier
        .width(72.dp)
        .height(72.dp)
        .heightIn(min = 100.dp)
                                    ) {
                                        Column(
                                            modifier = Modifier
        .heightIn(min = 100.dp)
        .offset(x = 0.dp, y = -(0.dp)),
                                            horizontalAlignment = Alignment.CenterHorizontally,
                                            verticalArrangement = Arrangement.Top
                                        ) {
                                            Column(
                                                modifier = Modifier
        .heightIn(min = 100.dp),
                                                horizontalAlignment = Alignment.Start,
                                                verticalArrangement = Arrangement.Top
                                            ) {
                                                Text(
                                                    text = "0",
                                                    fontWeight = FontWeight.Bold,
                                                    modifier = Modifier
                                                )
                                                Text(
                                                    text = "/150",
                                                    fontSize = 10.sp,
                                                    color = AppTheme.TextMedium,
                                                    modifier = Modifier
                                                )
                                            }
                                            Text(
                                                text = "gr",
                                                style = MaterialTheme.typography.bodyMedium.copy(color = AppTheme.TextLow),
                                                modifier = Modifier
                                            )
                                        }
                                        Row(
                                            modifier = Modifier.fillMaxSize(),
                                            verticalAlignment = Alignment.CenterVertically,
                                            horizontalArrangement = Arrangement.Start
                                        ) {
                                            Box(
                                                contentAlignment = Alignment.Center,
                                                modifier = Modifier.size(48.dp)
                                            ) {
                                                CircularProgressIndicator(
                                                    progress = 1.00f,
                                                    color = AppTheme.BorderDivider,
                                                    strokeWidth = 8.dp,
                                                    strokeCap = StrokeCap.Butt,
                                                    modifier = Modifier.fillMaxSize()
                                                )
                                                CircularProgressIndicator(
                                                    progress = 0.00f,
                                                    color = Color(0xFFFF9A1F),
                                                    strokeWidth = 8.dp,
                                                    strokeCap = StrokeCap.Round,
                                                    modifier = Modifier.fillMaxSize()
                                                )
                                            }
                                        }
                                    }
                                    Column(
                                        modifier = Modifier
        .heightIn(min = 100.dp),
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        verticalArrangement = Arrangement.Top
                                    ) {
                                        Text(
                                            text = "Power",
                                            fontSize = 14.sp,
                                            color = AppTheme.TextHigh,
                                            fontWeight = FontWeight.Medium,
                                            modifier = Modifier
                                        )
                                        Text(
                                            text = "Carbs",
                                            style = MaterialTheme.typography.bodyMedium.copy(color = AppTheme.TextMedium),
                                            modifier = Modifier
                                        )
                                    }
                                }
                            }
                            Box(modifier = Modifier.weight(1f)) {
                                Column(
                                    modifier = Modifier
        .heightIn(min = 100.dp),
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    Box(
                                        modifier = Modifier
        .width(72.dp)
        .height(72.dp)
        .heightIn(min = 100.dp)
                                    ) {
                                        Column(
                                            modifier = Modifier
        .heightIn(min = 100.dp)
        .offset(x = 0.dp, y = -(0.dp)),
                                            horizontalAlignment = Alignment.CenterHorizontally,
                                            verticalArrangement = Arrangement.Top
                                        ) {
                                            Column(
                                                modifier = Modifier
        .heightIn(min = 100.dp),
                                                horizontalAlignment = Alignment.Start,
                                                verticalArrangement = Arrangement.Top
                                            ) {
                                                Text(
                                                    text = "0",
                                                    fontWeight = FontWeight.Bold,
                                                    modifier = Modifier
                                                )
                                                Text(
                                                    text = "/113",
                                                    fontSize = 10.sp,
                                                    color = AppTheme.TextMedium,
                                                    modifier = Modifier
                                                )
                                            }
                                            Text(
                                                text = "gr",
                                                style = MaterialTheme.typography.bodyMedium.copy(color = AppTheme.TextLow),
                                                modifier = Modifier
                                            )
                                        }
                                        Row(
                                            modifier = Modifier.fillMaxSize(),
                                            verticalAlignment = Alignment.CenterVertically,
                                            horizontalArrangement = Arrangement.Start
                                        ) {
                                            Box(
                                                contentAlignment = Alignment.Center,
                                                modifier = Modifier.size(48.dp)
                                            ) {
                                                CircularProgressIndicator(
                                                    progress = 1.00f,
                                                    color = AppTheme.BorderDivider,
                                                    strokeWidth = 8.dp,
                                                    strokeCap = StrokeCap.Butt,
                                                    modifier = Modifier.fillMaxSize()
                                                )
                                                CircularProgressIndicator(
                                                    progress = 0.00f,
                                                    color = Color(0xFFFF9A1F),
                                                    strokeWidth = 8.dp,
                                                    strokeCap = StrokeCap.Round,
                                                    modifier = Modifier.fillMaxSize()
                                                )
                                            }
                                        }
                                    }
                                    Column(
                                        modifier = Modifier
        .heightIn(min = 100.dp),
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        verticalArrangement = Arrangement.Top
                                    ) {
                                        Text(
                                            text = "Protein",
                                            fontSize = 14.sp,
                                            color = AppTheme.TextHigh,
                                            fontWeight = FontWeight.Medium,
                                            modifier = Modifier
                                        )
                                        Text(
                                            text = "Power",
                                            style = MaterialTheme.typography.bodyMedium.copy(color = AppTheme.TextMedium),
                                            modifier = Modifier
                                        )
                                    }
                                }
                            }
                            Box(modifier = Modifier.weight(1f)) {
                                Column(
                                    modifier = Modifier
        .heightIn(min = 100.dp),
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    Box(
                                        modifier = Modifier
        .width(72.dp)
        .height(72.dp)
        .heightIn(min = 100.dp)
                                    ) {
                                        Column(
                                            modifier = Modifier
        .heightIn(min = 100.dp)
        .offset(x = 0.dp, y = -(0.dp)),
                                            horizontalAlignment = Alignment.CenterHorizontally,
                                            verticalArrangement = Arrangement.Top
                                        ) {
                                            Column(
                                                modifier = Modifier
        .heightIn(min = 100.dp),
                                                horizontalAlignment = Alignment.Start,
                                                verticalArrangement = Arrangement.Top
                                            ) {
                                                Text(
                                                    text = "0",
                                                    fontWeight = FontWeight.Bold,
                                                    modifier = Modifier
                                                )
                                                Text(
                                                    text = "/50",
                                                    fontSize = 10.sp,
                                                    color = AppTheme.TextMedium,
                                                    modifier = Modifier
                                                )
                                            }
                                            Text(
                                                text = "gr",
                                                style = MaterialTheme.typography.bodyMedium.copy(color = AppTheme.TextLow),
                                                modifier = Modifier
                                            )
                                        }
                                        Row(
                                            modifier = Modifier.fillMaxSize(),
                                            verticalAlignment = Alignment.CenterVertically,
                                            horizontalArrangement = Arrangement.Start
                                        ) {
                                            Box(
                                                contentAlignment = Alignment.Center,
                                                modifier = Modifier.size(48.dp)
                                            ) {
                                                CircularProgressIndicator(
                                                    progress = 1.00f,
                                                    color = AppTheme.BorderDivider,
                                                    strokeWidth = 8.dp,
                                                    strokeCap = StrokeCap.Butt,
                                                    modifier = Modifier.fillMaxSize()
                                                )
                                                CircularProgressIndicator(
                                                    progress = 0.00f,
                                                    color = Color(0xFFFF9A1F),
                                                    strokeWidth = 8.dp,
                                                    strokeCap = StrokeCap.Round,
                                                    modifier = Modifier.fillMaxSize()
                                                )
                                            }
                                        }
                                    }
                                    Column(
                                        modifier = Modifier
        .heightIn(min = 100.dp),
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        verticalArrangement = Arrangement.Top
                                    ) {
                                        Text(
                                            text = "Healthy",
                                            fontSize = 14.sp,
                                            color = AppTheme.TextHigh,
                                            fontWeight = FontWeight.Medium,
                                            modifier = Modifier
                                        )
                                        Text(
                                            text = "Fat",
                                            style = MaterialTheme.typography.bodyMedium.copy(color = AppTheme.TextMedium),
                                            modifier = Modifier
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
                Column(
                    modifier = Modifier
        .fillMaxWidth(),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(12.dp)
                    ) {
                        Box(modifier = Modifier.weight(1f)) {
                            Column(
                                modifier = Modifier
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(Color(0xFFD8D2FF))
        .padding(start = 16.dp, top = 16.dp, end = 16.dp, bottom = 16.dp),
                                horizontalAlignment = Alignment.Start,
                                verticalArrangement = Arrangement.spacedBy(12.dp)
                            ) {
                                Row(
                                    modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Row(
                                        modifier = Modifier
        .width(56.dp)
        .height(56.dp)
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(9999.dp))
        .background(Color(red = 255/255f, green = 255/255f, blue = 255/255f, alpha = 0.55f)),
                                        verticalAlignment = Alignment.CenterVertically,
                                        horizontalArrangement = Arrangement.Start
                                    ) {
                                        AsyncImage(
                                            model = "https://pub-7c8c3c7444724a39ba3eeb8accbbca4a.r2.dev/visual-assets/b8041495-1552-4079-9c20-80bd656e240f/display_1024.png",
                                            contentDescription = null,
                                            contentScale = ContentScale.Crop,
                                            modifier = Modifier
                                        )
                                    }
                                    Text(
                                        text = "631 kcal",
                                        fontSize = 18.sp,
                                        color = AppTheme.TextHigh,
                                        fontWeight = FontWeight.Medium,
                                        modifier = Modifier
                                    )
                                }
                                Row(
                                    modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                    verticalAlignment = Alignment.Bottom,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(
                                        text = "Breakfast",
                                        style = MaterialTheme.typography.titleLarge.copy(color = AppTheme.TextHigh),
                                        modifier = Modifier
                                    )
                                    Button(
                                        onClick = { /* Action */ },
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF5F5FA)),
                                        shape = RoundedCornerShape(9999.dp),
                                        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                                        modifier = Modifier
                                    ) {
                                        Row(
                                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                                            verticalAlignment = Alignment.CenterVertically
                                        ) {
                                            Icon(
                                                imageVector = Icons.Default.Plus, // Lucide: plus
                                                contentDescription = null,
                                                tint = AppTheme.TextHigh,
                                                modifier = Modifier
        .size(24.dp)
                                            )
                                        }
                                    }
                                }
                            }
                        }
                        Box(modifier = Modifier.weight(1f)) {
                            Column(
                                modifier = Modifier
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(Color(0xFFFFE680))
        .padding(start = 16.dp, top = 16.dp, end = 16.dp, bottom = 16.dp),
                                horizontalAlignment = Alignment.Start,
                                verticalArrangement = Arrangement.spacedBy(12.dp)
                            ) {
                                Row(
                                    modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Row(
                                        modifier = Modifier
        .width(56.dp)
        .height(56.dp)
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(9999.dp))
        .background(Color(red = 255/255f, green = 255/255f, blue = 255/255f, alpha = 0.55f)),
                                        verticalAlignment = Alignment.CenterVertically,
                                        horizontalArrangement = Arrangement.Start
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Salad, // Lucide: salad
                                            contentDescription = null,
                                            tint = Color(0xFF7A6B2E),
                                            modifier = Modifier
        .size(24.dp)
                                        )
                                    }
                                    Text(
                                        text = "486 kcal",
                                        fontSize = 18.sp,
                                        color = AppTheme.TextHigh,
                                        fontWeight = FontWeight.Medium,
                                        modifier = Modifier
                                    )
                                }
                                Row(
                                    modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                    verticalAlignment = Alignment.Bottom,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(
                                        text = "Lunch",
                                        style = MaterialTheme.typography.titleLarge.copy(color = AppTheme.TextHigh),
                                        modifier = Modifier
                                    )
                                    Button(
                                        onClick = { /* Action */ },
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF5F5FA)),
                                        shape = RoundedCornerShape(9999.dp),
                                        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                                        modifier = Modifier
                                    ) {
                                        Row(
                                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                                            verticalAlignment = Alignment.CenterVertically
                                        ) {
                                            Icon(
                                                imageVector = Icons.Default.Plus, // Lucide: plus
                                                contentDescription = null,
                                                tint = AppTheme.TextHigh,
                                                modifier = Modifier
        .size(24.dp)
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    }
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(12.dp)
                    ) {
                        Box(modifier = Modifier.weight(1f)) {
                            Column(
                                modifier = Modifier
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(Color(0xFFB6F1C8))
        .padding(start = 16.dp, top = 16.dp, end = 16.dp, bottom = 16.dp),
                                horizontalAlignment = Alignment.Start,
                                verticalArrangement = Arrangement.spacedBy(12.dp)
                            ) {
                                Row(
                                    modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Row(
                                        modifier = Modifier
        .width(56.dp)
        .height(56.dp)
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(9999.dp))
        .background(Color(red = 255/255f, green = 255/255f, blue = 255/255f, alpha = 0.55f)),
                                        verticalAlignment = Alignment.CenterVertically,
                                        horizontalArrangement = Arrangement.Start
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Utensils, // Lucide: utensils
                                            contentDescription = null,
                                            tint = Color(0xFF2F6A47),
                                            modifier = Modifier
        .size(24.dp)
                                        )
                                    }
                                    Text(
                                        text = "359 kcal",
                                        fontSize = 18.sp,
                                        color = AppTheme.TextHigh,
                                        fontWeight = FontWeight.Medium,
                                        modifier = Modifier
                                    )
                                }
                                Row(
                                    modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                    verticalAlignment = Alignment.Bottom,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(
                                        text = "Dinner",
                                        style = MaterialTheme.typography.titleLarge.copy(color = AppTheme.TextHigh),
                                        modifier = Modifier
                                    )
                                    Button(
                                        onClick = { /* Action */ },
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF5F5FA)),
                                        shape = RoundedCornerShape(9999.dp),
                                        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                                        modifier = Modifier
                                    ) {
                                        Row(
                                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                                            verticalAlignment = Alignment.CenterVertically
                                        ) {
                                            Icon(
                                                imageVector = Icons.Default.Plus, // Lucide: plus
                                                contentDescription = null,
                                                tint = AppTheme.TextHigh,
                                                modifier = Modifier
        .size(24.dp)
                                            )
                                        }
                                    }
                                }
                            }
                        }
                        Box(modifier = Modifier.weight(1f)) {
                            Column(
                                modifier = Modifier
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(AppTheme.BorderRadiusApp))
        .background(Color(0xFFFFCBA4))
        .padding(start = 16.dp, top = 16.dp, end = 16.dp, bottom = 16.dp),
                                horizontalAlignment = Alignment.Start,
                                verticalArrangement = Arrangement.spacedBy(12.dp)
                            ) {
                                Row(
                                    modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Row(
                                        modifier = Modifier
        .width(56.dp)
        .height(56.dp)
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(9999.dp))
        .background(Color(red = 255/255f, green = 255/255f, blue = 255/255f, alpha = 0.55f)),
                                        verticalAlignment = Alignment.CenterVertically,
                                        horizontalArrangement = Arrangement.Start
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Cookie, // Lucide: cookie
                                            contentDescription = null,
                                            tint = Color(0xFF7A4521),
                                            modifier = Modifier
        .size(24.dp)
                                        )
                                    }
                                    Text(
                                        text = "193 kcal",
                                        fontSize = 18.sp,
                                        color = AppTheme.TextHigh,
                                        fontWeight = FontWeight.Medium,
                                        modifier = Modifier
                                    )
                                }
                                Row(
                                    modifier = Modifier
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                    verticalAlignment = Alignment.Bottom,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(
                                        text = "Snack",
                                        style = MaterialTheme.typography.titleLarge.copy(color = AppTheme.TextHigh),
                                        modifier = Modifier
                                    )
                                    Button(
                                        onClick = { /* Action */ },
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF5F5FA)),
                                        shape = RoundedCornerShape(9999.dp),
                                        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                                        modifier = Modifier
                                    ) {
                                        Row(
                                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                                            verticalAlignment = Alignment.CenterVertically
                                        ) {
                                            Icon(
                                                imageVector = Icons.Default.Plus, // Lucide: plus
                                                contentDescription = null,
                                                tint = AppTheme.TextHigh,
                                                modifier = Modifier
        .size(24.dp)
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Column(
            modifier = Modifier
        .heightIn(min = 100.dp),
            horizontalAlignment = Alignment.Start,
            verticalArrangement = Arrangement.Top
        ) {
        }
    }
        }
    Row(
        modifier = Modifier
        .heightIn(min = 100.dp)
        .clip(RoundedCornerShape(999.dp))
        .background(Color(red = 255/255f, green = 255/255f, blue = 255/255f, alpha = 0.92f))
        .border(1.dp, Color(red = 0/255f, green = 0/255f, blue = 0/255f, alpha = 0.05f), RoundedCornerShape(999.dp))
        .padding(start = 8.dp, top = 8.dp, end = 8.dp, bottom = 8.dp)
        .align(Alignment.BottomCenter).fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.Start
    ) {
        Column(
            modifier = Modifier
        .background(Color(0xFFF5F5FA)),
            verticalArrangement = Arrangement.spacedBy(4.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Box(modifier = Modifier.weight(1f)) {
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                        shape = RoundedCornerShape(999.dp),
                        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(3.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Row(
                                modifier = Modifier
        .width(18.dp)
        .height(18.dp)
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.Start
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Home, // Lucide: home
                                    contentDescription = null,
                                    tint = Color.Transparent,
                                    modifier = Modifier
        .size(24.dp)
                                )
                            }
                            Text(
                                text = "Meal Plan",
                                modifier = Modifier
                            )
                        }
                    }
                }
                Box(modifier = Modifier.weight(1f)) {
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                        shape = RoundedCornerShape(999.dp),
                        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(3.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Row(
                                modifier = Modifier
        .width(18.dp)
        .height(18.dp)
        .heightIn(min = 100.dp)
        .background(Color(0xFFF5F5FA)),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.Start
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Search, // Lucide: search
                                    contentDescription = null,
                                    tint = Color.Transparent,
                                    modifier = Modifier
        .size(24.dp)
                                )
                            }
                            Text(
                                text = "Journal",
                                modifier = Modifier
                            )
                        }
                    }
                }
            }
        }
    }
    }
}
