//
// AppTheme.js
// Drawgle Auto-generated
//

export const AppTheme = {
  colors: {
    backgroundPrimary: '#FFFFFF',
    backgroundSecondary: '#F3F4F6',
    surfaceCard: '#FFFFFF',
    actionPrimary: '#3B82F6',
    actionOnPrimary: '#FFFFFF',
    textHigh: '#111827',
    textMedium: '#4B5563',
    textLow: '#9CA3AF',
    borderDivider: '#E5E7EB',
  },
  radii: {
    app: 18,
    pill: 9999,
  },
  layout: {
    screenPadding: 24,
    sectionGap: 24,
    elementGap: 16,
  }
};

//
// JournalScreen.tsx
// Auto-generated by Drawgle
//

import React from 'react';
import {
  StyleSheet,
  Text,
  View,
  Image,
  ScrollView,
  TouchableOpacity,
  SafeAreaView
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { AppTheme } from './AppTheme';

// Visual icon placeholder
function Icon({ name, size = 24, color = '#000' }: { name: string; size?: number; color?: string }) {
  return (
    <View style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }}>
      <Text style={{ color, fontSize: size * 0.8, fontWeight: 'bold' }}>•</Text>
    </View>
  );
}

export default function JournalScreen() {
  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: AppTheme.colors.backgroundPrimary }}>
      <View style={{ flex: 1 }}>
      <ScrollView contentContainerStyle={{ flexGrow: 1 }}>
  <View style={{
    flexDirection: 'column',
    width: '100%',
    backgroundColor: AppTheme.colors.backgroundPrimary,
  }}>
    <View style={{
      flexDirection: 'column',
      flex: 1,
      paddingTop: 16,
      paddingBottom: 96,
    }}>
      <View style={{
        flexDirection: 'column',
        paddingHorizontal: AppTheme.layout.screenPadding,
      }}>
        <Text style={{
          fontSize: 24,
          color: AppTheme.colors.textHigh,
          fontWeight: 'bold',
          marginBottom: AppTheme.layout.sectionGap,
        }}>
          Journal
        </Text>
        <View style={{
          flexDirection: 'column',
          backgroundColor: AppTheme.colors.surfaceCard,
          borderRadius: AppTheme.radii.app,
        }}>
          <View style={{
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
          }}>
            <View style={{
              flexDirection: 'row',
              alignItems: 'center',
            }}>
              <View style={{
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
                width: 36,
                height: 36,
                backgroundColor: AppTheme.colors.backgroundPrimary,
                borderRadius: 9999,
              }}>
                <Icon name="flame" size={24} color={'var(--dg-color-action-accent-coral)'} />
              </View>
              <View style={{
                flexDirection: 'column',
              }}>
                <Text style={{
                  fontSize: 18,
                  color: AppTheme.colors.textHigh,
                  fontWeight: 'bold',
                }}>
                  Calories
                </Text>
                <Text style={{
                  fontSize: 12,
                  color: AppTheme.colors.textMedium,
                  fontWeight: 'bold',
                }}>
                  Week Days
                </Text>
              </View>
            </View>
            <TouchableOpacity 
              onPress={() => {}}
              style={{
                backgroundColor: AppTheme.colors.backgroundPrimary,
                borderRadius: 9999,
                paddingVertical: 12,
                paddingHorizontal: 16,
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <Icon name="calendar" size={24} color={AppTheme.colors.textHigh} />
            </TouchableOpacity>
          </View>
          <View style={{
            flexDirection: 'column',
          }}>
            <View style={{
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
              backgroundColor: AppTheme.colors.backgroundPrimary,
              borderRadius: 20,
              paddingTop: 12,
              paddingBottom: 12,
            }}>
              <Text style={{
                fontSize: 16,
                color: AppTheme.colors.textMedium,
                fontWeight: '500',
              }}>
                Consumed
              </Text>
              <Text style={{
                fontSize: 32,
                color: AppTheme.colors.textHigh,
                fontWeight: 'bold',
              }}>
                00 cal
              </Text>
            </View>
            <View style={{
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
              backgroundColor: AppTheme.colors.backgroundPrimary,
              borderRadius: 20,
              paddingTop: 12,
              paddingBottom: 12,
            }}>
              <Text style={{
                fontSize: 16,
                color: AppTheme.colors.textMedium,
                fontWeight: '500',
              }}>
                Remaining
              </Text>
              <Text style={{
                fontSize: 32,
                color: AppTheme.colors.textHigh,
                fontWeight: 'bold',
              }}>
                00 cal
              </Text>
            </View>
            <View style={{
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
              backgroundColor: AppTheme.colors.backgroundPrimary,
              borderRadius: 20,
              paddingTop: 12,
              paddingBottom: 12,
            }}>
              <LinearGradient
                colors={['transparent', 'rgba(0, 0, 0, 0.03)']}
                start={{ x: 0, y: 1 }}
                end={{ x: 1, y: 0 }}
                style={{
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                flexDirection: 'column',
              }}>
              </LinearGradient>
              <Text style={{
                fontSize: 16,
                color: AppTheme.colors.textLow,
                fontWeight: '500',
              }}>
                Remaining
              </Text>
              <Text style={{
                fontSize: 32,
                color: AppTheme.colors.textLow,
                fontWeight: 'bold',
              }}>
                00 cal
              </Text>
            </View>
          </View>
          <View style={{
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
          }}>
            <View style={{
              flexDirection: 'column',
              alignItems: 'center',
              flex: 1,
            }}>
              <View style={{
                flexDirection: 'column',
                width: 64,
                height: 64,
              }}>
                <View style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  right: 0,
                  bottom: 0,
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}>
                  <Icon name="wheat" size={24} color={'var(--dg-color-action-accent-coral)'} />
                </View>
                <View style={{ width: 48, height: 48 }}>{/* TODO: Add custom SVG/Asset */}</View>
              </View>
              <View style={{
                flexDirection: 'column',
              }}>
                <Text>0/150</Text>
                <Text style={{
                  fontSize: 12,
                  color: AppTheme.colors.textLow,
                }}>
                  gr
                </Text>
              </View>
              <Text style={{
                fontSize: 12,
                color: AppTheme.colors.textMedium,
                fontWeight: 'bold',
                marginTop: 2,
              }}>
                Power Carbs
              </Text>
            </View>
            <View style={{
              flexDirection: 'column',
              alignItems: 'center',
              flex: 1,
            }}>
              <View style={{
                flexDirection: 'column',
                width: 64,
                height: 64,
              }}>
                <View style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  right: 0,
                  bottom: 0,
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}>
                  <Icon name="egg" size={24} color={'var(--dg-color-action-accent-coral)'} />
                </View>
                <View style={{ width: 48, height: 48 }}>{/* TODO: Add custom SVG/Asset */}</View>
              </View>
              <View style={{
                flexDirection: 'column',
              }}>
                <Text>0/113</Text>
                <Text style={{
                  fontSize: 12,
                  color: AppTheme.colors.textLow,
                }}>
                  gr
                </Text>
              </View>
              <Text style={{
                fontSize: 12,
                color: AppTheme.colors.textMedium,
                fontWeight: 'bold',
                marginTop: 2,
              }}>
                Protein Power
              </Text>
            </View>
            <View style={{
              flexDirection: 'column',
              alignItems: 'center',
              flex: 1,
            }}>
              <View style={{
                flexDirection: 'column',
                width: 64,
                height: 64,
              }}>
                <View style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  right: 0,
                  bottom: 0,
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}>
                  <Icon name="droplet" size={24} color={'var(--dg-color-action-accent-coral)'} />
                </View>
                <View style={{ width: 48, height: 48 }}>{/* TODO: Add custom SVG/Asset */}</View>
              </View>
              <View style={{
                flexDirection: 'column',
              }}>
                <Text>0/50</Text>
                <Text style={{
                  fontSize: 12,
                  color: AppTheme.colors.textLow,
                }}>
                  gr
                </Text>
              </View>
              <Text style={{
                fontSize: 12,
                color: AppTheme.colors.textMedium,
                fontWeight: 'bold',
                marginTop: 2,
              }}>
                Healthy Fat
              </Text>
            </View>
          </View>
        </View>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: AppTheme.layout.elementGap }}>
          <View style={{
            width: '48%',
            flexDirection: 'column',
            justifyContent: 'space-between',
            minHeight: 120,
            backgroundColor: 'var(--dg-color-surface-pastel-lavender)',
            borderRadius: AppTheme.radii.app,
          }}>
            <View style={{
              width: '48%',
              flexDirection: 'row',
              alignItems: 'flex-start',
              justifyContent: 'space-between',
            }}>
              <Image 
                source={{ uri: 'https://pub-7c8c3c7444724a39ba3eeb8accbbca4a.r2.dev/visual-assets/b8041495-1552-4079-9c20-80bd656e240f/display_1024.png' }}
                alt="Small bowl of cereal or fruit"
                style={{
                  width: '48%',
                  height: 44,
                  borderRadius: 9999,
                }}
              />
              <Text style={{
                width: '48%',
                fontSize: 14,
                color: AppTheme.colors.textHigh,
                fontWeight: 'normal',
              }}>
                631 kcal
              </Text>
            </View>
            <View style={{
              width: '48%',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}>
              <Text style={{
                width: '48%',
                fontSize: 16,
                color: AppTheme.colors.textHigh,
                fontWeight: '500',
              }}>
                Breakfast
              </Text>
              <TouchableOpacity 
                onPress={() => {}}
                style={{
                  width: '48%',
                  backgroundColor: '#FFFFFF',
                  borderRadius: 9999,
                  paddingVertical: 12,
                  paddingHorizontal: 16,
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <Icon name="plus" size={24} color={AppTheme.colors.textHigh} />
              </TouchableOpacity>
            </View>
          </View>
          <View style={{
            width: '48%',
            flexDirection: 'column',
            justifyContent: 'space-between',
            minHeight: 120,
            backgroundColor: 'var(--dg-color-surface-pastel-butter)',
            borderRadius: AppTheme.radii.app,
          }}>
            <View style={{
              width: '48%',
              flexDirection: 'row',
              alignItems: 'flex-start',
              justifyContent: 'space-between',
            }}>
              <View style={{
                width: '48%',
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
                height: 44,
                borderRadius: 9999,
              }}>
                <Icon name="salad" size={24} color={AppTheme.colors.textMedium} />
              </View>
              <Text style={{
                width: '48%',
                fontSize: 14,
                color: AppTheme.colors.textHigh,
                fontWeight: 'normal',
              }}>
                486 kcal
              </Text>
            </View>
            <View style={{
              width: '48%',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}>
              <Text style={{
                width: '48%',
                fontSize: 16,
                color: AppTheme.colors.textHigh,
                fontWeight: '500',
              }}>
                Lunch
              </Text>
              <TouchableOpacity 
                onPress={() => {}}
                style={{
                  width: '48%',
                  backgroundColor: '#FFFFFF',
                  borderRadius: 9999,
                  paddingVertical: 12,
                  paddingHorizontal: 16,
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <Icon name="plus" size={24} color={AppTheme.colors.textHigh} />
              </TouchableOpacity>
            </View>
          </View>
          <View style={{
            width: '48%',
            flexDirection: 'column',
            justifyContent: 'space-between',
            minHeight: 120,
            backgroundColor: 'var(--dg-color-surface-pastel-mint)',
            borderRadius: AppTheme.radii.app,
          }}>
            <View style={{
              width: '48%',
              flexDirection: 'row',
              alignItems: 'flex-start',
              justifyContent: 'space-between',
            }}>
              <View style={{
                width: '48%',
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
                height: 44,
                borderRadius: 9999,
              }}>
                <Icon name="soup" size={24} color={AppTheme.colors.textMedium} />
              </View>
              <Text style={{
                width: '48%',
                fontSize: 14,
                color: AppTheme.colors.textHigh,
                fontWeight: 'normal',
              }}>
                359 kcal
              </Text>
            </View>
            <View style={{
              width: '48%',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}>
              <Text style={{
                width: '48%',
                fontSize: 16,
                color: AppTheme.colors.textHigh,
                fontWeight: '500',
              }}>
                Dinner
              </Text>
              <TouchableOpacity 
                onPress={() => {}}
                style={{
                  width: '48%',
                  backgroundColor: '#FFFFFF',
                  borderRadius: 9999,
                  paddingVertical: 12,
                  paddingHorizontal: 16,
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <Icon name="plus" size={24} color={AppTheme.colors.textHigh} />
              </TouchableOpacity>
            </View>
          </View>
          <View style={{
            width: '48%',
            flexDirection: 'column',
            justifyContent: 'space-between',
            minHeight: 120,
            backgroundColor: '#FFE0B2',
            borderRadius: AppTheme.radii.app,
          }}>
            <View style={{
              width: '48%',
              flexDirection: 'row',
              alignItems: 'flex-start',
              justifyContent: 'space-between',
            }}>
              <View style={{
                width: '48%',
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
                height: 44,
                borderRadius: 9999,
              }}>
                <Icon name="cookie" size={24} color={AppTheme.colors.textMedium} />
              </View>
              <Text style={{
                width: '48%',
                fontSize: 14,
                color: AppTheme.colors.textHigh,
                fontWeight: 'normal',
              }}>
                193 kcal
              </Text>
            </View>
            <View style={{
              width: '48%',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}>
              <Text style={{
                width: '48%',
                fontSize: 16,
                color: AppTheme.colors.textHigh,
                fontWeight: '500',
              }}>
                Snack
              </Text>
              <TouchableOpacity 
                onPress={() => {}}
                style={{
                  width: '48%',
                  backgroundColor: '#FFFFFF',
                  borderRadius: 9999,
                  paddingVertical: 12,
                  paddingHorizontal: 16,
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <Icon name="plus" size={24} color={AppTheme.colors.textHigh} />
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </View>
    </View>
  </View>
      </ScrollView>
  <View style={{
    flexDirection: 'column',
    paddingHorizontal: AppTheme.layout.screenPadding,
    paddingBottom: 16,
  }}>
    <View style={{
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      height: 80,
      backgroundColor: 'var(--dg-color-surface-glass-nav)',
      borderRadius: AppTheme.radii.pill,
      borderWidth: 1,
      borderColor: AppTheme.colors.borderDivider,
    }}>
      <TouchableOpacity 
        onPress={() => {}}
        style={{
          paddingVertical: 12,
          paddingHorizontal: 16,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Icon name="chef-hat" size={24} color={AppTheme.colors.textLow} />
      </TouchableOpacity>
      <TouchableOpacity 
        onPress={() => {}}
        style={{
          paddingVertical: 12,
          paddingHorizontal: 16,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Icon name="calendar-days" size={24} color={AppTheme.colors.textLow} />
      </TouchableOpacity>
      <TouchableOpacity 
        onPress={() => {}}
        style={{
          paddingVertical: 12,
          paddingHorizontal: 16,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Icon name="sparkles" size={24} color={AppTheme.colors.textLow} />
      </TouchableOpacity>
      <TouchableOpacity 
        onPress={() => {}}
        style={{
          paddingVertical: 12,
          paddingHorizontal: 16,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <View style={{
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          width: 44,
          height: 44,
          backgroundColor: AppTheme.colors.actionPrimary,
          borderRadius: 9999,
        }}>
          <Icon name="book-open" size={24} color={AppTheme.colors.actionOnPrimary} />
        </View>
      </TouchableOpacity>
      <TouchableOpacity 
        onPress={() => {}}
        style={{
          paddingVertical: 12,
          paddingHorizontal: 16,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Icon name="book-marked" size={24} color={AppTheme.colors.textLow} />
      </TouchableOpacity>
    </View>
  </View>
      </View>
    </SafeAreaView>
  );
}
