export const siteConfig = {
  name: "Drawgle",
  baseUrl: "https://drawgle.com",
  defaultTitle: "Drawgle - AI Mobile UI Design Tool",
  defaultDescription:
    "Design premium mobile app interfaces, then export agent-ready HTML, design tokens, and implementation context for your coding workflow.",
  supportEmail: "support@drawgle.com",
  creatorHandle: "@9to5_Dad",
  sameAs: ["https://x.com/9to5_Dad"],
  defaultOgImage: {
    path: "/bg-image.webp",
    width: 1200,
    height: 630,
    alt: "Drawgle - AI Mobile UI Design Tool",
  },
  keywords: [
    "AI mobile UI design",
    "app UI generator",
    "image to UI",
    "mobile app design",
    "agent-ready UI handoff",
    "HTML Tailwind export",
  ],
  publicRoutes: [
    {
      path: "/",
      title: "Drawgle - AI Mobile UI Design Tool",
      description:
        "Design premium mobile app interfaces, then export agent-ready HTML, design tokens, and implementation context for your coding workflow.",
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      path: "/pricing",
      title: "Pricing - Simple plans for builders",
      description:
        "Choose the perfect plan to turn prompts and screenshots into clean, exportable Tailwind HTML code with complete design token control.",
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      path: "/showcase",
      title: "AI-Generated Mobile UI Showcase",
      description:
        "Explore premium mobile app screens generated by Drawgle across finance, commerce, fitness, productivity, security, and more.",
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      path: "/terms",
      title: "Terms of Service",
      description: "Terms governing your use of Drawgle's AI mobile UI design service.",
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      path: "/privacy-policy",
      title: "Privacy Policy",
      description: "How Drawgle collects, uses, stores, and protects personal data.",
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      path: "/refunds-policy",
      title: "Refund Policy",
      description: "Drawgle's policy for subscription cancellations, refund requests, and AI credits.",
      changeFrequency: "monthly",
      priority: 0.4,
    },
  ] as const,
  pricing: [
    {
      name: "Starter",
      description: "For builders exploring prompt-to-UI and screenshot-to-UI workflows.",
      price: "9",
      currency: "USD",
      url: "/pricing",
    },
    {
      name: "Pro",
      description: "For creators producing larger mobile UI projects with native app scaffolds.",
      price: "29",
      currency: "USD",
      url: "/pricing",
    },
    {
      name: "Studio",
      description: "For teams and power users with high-volume mobile UI generation needs.",
      price: "79",
      currency: "USD",
      url: "/pricing",
    },
  ] as const,
} as const;

export type PublicRoutePath = (typeof siteConfig.publicRoutes)[number]["path"];

export function absoluteUrl(path = "/") {
  return new URL(path, siteConfig.baseUrl).toString();
}
