"use client";

import React, { useState, useMemo } from "react";
import { Copy, Check, Download, Smartphone, X, Terminal, Cpu, Sparkles, Loader2 } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import type { DesignTokens } from "@/lib/types";
import {
  parseScreenHtml,
  generateTokenHeaderComment,
  transpileToSwiftUI,
  transpileToCompose,
  transpileToReactNative,
  transpileToFlutter,
  TranspileNode
} from "@/lib/mobile-transpiler";

interface MobileExportDrawerProps {
  open: boolean;
  onClose: () => void;
  screenCode: string;
  navigationCode: string;
  screenName: string;
  designTokens?: DesignTokens | null;
}

type MobileFramework = "swiftui" | "compose" | "reactnative" | "flutter";

export function MobileExportDrawer({
  open,
  onClose,
  screenCode,
  navigationCode,
  screenName,
  designTokens
}: MobileExportDrawerProps) {
  const [activeTab, setActiveTab] = useState<MobileFramework>("swiftui");
  const [copied, setCopied] = useState(false);

  // Clean screen and file names
  const cleanScreenName = useMemo(() => {
    return screenName.replace(/[^a-zA-Z0-9]/g, "");
  }, [screenName]);

  const fileExtensions: Record<MobileFramework, string> = {
    swiftui: "swift",
    compose: "kt",
    reactnative: "tsx",
    flutter: "dart"
  };

  // Compile the transpiled AST and frameworks once screenCode changes
  const compiledCodes = useMemo(() => {
    if (!open || !screenCode) return null;

    try {
      // Combine screen html and navigation elements
      const combinedHtml = `<div>
        ${screenCode}
        ${navigationCode ? `<div id="drawgle-navigation-shell">${navigationCode}</div>` : ""}
      </div>`;

      const ast = parseScreenHtml(combinedHtml, designTokens);
      if (!ast) {
        throw new Error("Unable to parse HTML into structured DOM tree.");
      }

      const headers = generateTokenHeaderComment(designTokens);

      // Generate Swift Code
      const swiftUiView = `//\n//  ${cleanScreenName}View.swift\n//  Auto-generated by Drawgle\n//\n\nimport SwiftUI\n\nstruct ${cleanScreenName}View: View {\n    var body: some View {\n        ScrollView {\n` +
        transpileToSwiftUI(ast) +
        `        }\n        .background(AppTheme.backgroundPrimary)\n        .edgesIgnoringSafeArea(.all)\n    }\n}\n\n#Preview {\n    ${cleanScreenName}View()\n}\n`;

      const swiftFull = headers.swift + "\n" + swiftUiView;

      // Generate Jetpack Compose Code
      const composeView = `/*\n * ${cleanScreenName}Screen.kt\n * Auto-generated by Drawgle\n */\n\npackage com.drawgle.ui\n\nimport androidx.compose.foundation.layout.*\nimport androidx.compose.foundation.rememberScrollState\nimport androidx.compose.foundation.verticalScroll\nimport androidx.compose.runtime.Composable\nimport androidx.compose.ui.Modifier\nimport androidx.compose.ui.graphics.Color\nimport com.drawgle.theme.AppTheme\n\n@Composable\nfun ${cleanScreenName}Screen() {\n    Box(\n        modifier = Modifier\n            .fillMaxSize()\n            .background(AppTheme.BackgroundPrimary)\n    ) {\n        Column(\n            modifier = Modifier\n                .fillMaxSize()\n                .verticalScroll(rememberScrollState())\n        ) {\n` +
        transpileToCompose(ast) +
        `        }\n    }\n}\n`;

      const composeFull = headers.compose + "\n" + composeView;

      // Generate React Native Code
      const rnView = `//\n// ${cleanScreenName}Screen.tsx\n// Auto-generated by Drawgle\n//\n\nimport React from 'react';\nimport {\n  StyleSheet,\n  Text,\n  View,\n  Image,\n  ScrollView,\n  TouchableOpacity,\n  SafeAreaView\n} from 'react-native';\nimport { AppTheme } from './AppTheme';\n\n// Visual icon placeholder (feel free to swap with react-native-vector-icons or custom SVGs in production)\nfunction Icon({ name, size = 24, color = '#000' }: { name: string; size?: number; color?: string }) {\n  return (\n    <View style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }}>\n      <Text style={{ color, fontSize: size * 0.8, fontWeight: 'bold' }}>•</Text>\n    </View>\n  );\n}\n\nexport default function ${cleanScreenName}Screen() {\n  return (\n    <SafeAreaView style={{ flex: 1, backgroundColor: AppTheme.colors.backgroundPrimary }}>\n      <ScrollView contentContainerStyle={{ flexGrow: 1 }}>\n` +
        transpileToReactNative(ast) +
        `      </ScrollView>\n    </SafeAreaView>\n  );\n}\n`;

      const rnFull = headers.rn + "\n" + rnView;

      // Generate Flutter Code
      const flutterView = `//\n// ${cleanScreenName.toLowerCase()}_screen.dart\n// Auto-generated by Drawgle\n//\n\nimport 'package:flutter/material.dart';\nimport 'app_theme.dart';\n\nclass ${cleanScreenName}Screen extends StatelessWidget {\n  const ${cleanScreenName}Screen({Key? key}) : super(key: key);\n\n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      backgroundColor: AppTheme.backgroundPrimary,\n      body: SafeArea(\n        child: SingleChildScrollView(\n          child: ` +
        transpileToFlutter(ast).trim() +
        `,\n        ),\n      ),\n    );\n  }\n}\n`;

      const flutterFull = headers.flutter + "\n" + flutterView;

      return {
        swiftui: swiftFull,
        compose: composeFull,
        reactnative: rnFull,
        flutter: flutterFull,
        ast
      };
    } catch (err) {
      console.error("Transpilation failed", err);
      return null;
    }
  }, [open, screenCode, navigationCode, designTokens, cleanScreenName]);

  const activeCode = compiledCodes?.[activeTab] || "";

  const handleCopy = () => {
    if (!activeCode) return;
    navigator.clipboard.writeText(activeCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!activeCode) return;
    const blob = new Blob([activeCode], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${cleanScreenName}.${fileExtensions[activeTab]}`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <Sheet open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <SheetContent
        side="right"
        className="!w-full sm:!w-[540px] sm:!max-w-[540px] border-l border-slate-950/[0.1] bg-white p-0 text-slate-900 shadow-2xl overflow-hidden flex flex-col h-full"
      >
        <div className="flex h-full flex-col min-h-0">
          {/* Header */}
          <SheetHeader className="border-b border-slate-950/[0.08] bg-white px-6 pb-4 pt-6 shrink-0 space-y-0">
            <div className="flex items-center justify-between">
              <div>
                <SheetTitle className="text-[15px] font-semibold text-slate-950 text-left">
                  Export {screenName}
                </SheetTitle>
                <SheetDescription className="mt-1 text-[13px] text-slate-500 text-left">
                  Native mobile code for this screen.
                </SheetDescription>
              </div>
              
            </div>
            
            {/* Segmented Pill Selector Row matching ChatPanel.tsx */}
            <div className="mt-6 grid grid-cols-4 gap-1 rounded-[14px] bg-slate-950/[0.04] p-1">
              {(["swiftui", "compose", "reactnative", "flutter"] as MobileFramework[]).map((tab) => {
                const isActive = activeTab === tab;
                return (
                  <button
                    key={tab}
                    type="button"
                    onClick={() => setActiveTab(tab)}
                    className={`flex h-8 items-center justify-center rounded-[10px] text-[11px] font-semibold transition ${
                      isActive ? "bg-white text-slate-950 shadow-sm" : "text-slate-500 hover:text-slate-800"
                    }`}
                  >
                    {tab === "swiftui" && "SwiftUI"}
                    {tab === "compose" && "Compose"}
                    {tab === "reactnative" && "React Native"}
                    {tab === "flutter" && "Flutter"}
                  </button>
                );
              })}
            </div>
          </SheetHeader>

          {/* Content Area */}
          <div className="flex-1 min-h-0 bg-[#f7f7f8] px-4 py-4 flex flex-col">
            <div className="flex-1 min-h-0 flex flex-col rounded-[16px] border border-slate-950/[0.08] bg-white overflow-hidden shadow-sm">
              <div className="flex items-center justify-between border-b border-slate-950/[0.05] bg-white px-4 py-2 shrink-0">
                <div className="text-[12px] font-medium text-slate-500 font-mono">
                  {cleanScreenName}{activeTab === "swiftui" ? "View.swift" : activeTab === "compose" ? "Screen.kt" : activeTab === "reactnative" ? "Screen.tsx" : "_screen.dart"}
                </div>
              </div>
              <div className="flex-1 min-h-0 relative font-mono text-[12px] leading-relaxed">
                {compiledCodes ? (
                  <pre className="h-full w-full overflow-auto p-4 text-slate-700 select-text scrollbar-thin scrollbar-thumb-slate-200 scrollbar-track-transparent">
                    <code>{activeCode}</code>
                  </pre>
                ) : (
                  <div className="flex h-full flex-col items-center justify-center gap-3 text-center px-6">
                    <Loader2 className="h-5 w-5 text-slate-400 animate-spin" />
                    <div className="text-[13px] text-slate-500">Compiling native code...</div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Action CTAs Bottom Bar */}
          <div className="border-t border-slate-950/[0.08] bg-white px-5 py-3 flex items-center justify-end gap-2 shrink-0">
            <Button
              type="button"
              variant="outline"
              onClick={handleDownload}
              disabled={!activeCode}
              className="h-8 rounded-[10px] bg-white px-3 text-[12px] font-semibold text-slate-700 border-slate-950/[0.1] hover:bg-slate-50"
            >
              <Download className="mr-1.5 h-3.5 w-3.5" />
              Download
            </Button>
            <Button
              type="button"
              onClick={handleCopy}
              disabled={!activeCode}
              className="h-8 rounded-[10px] bg-slate-950 px-3 text-[12px] font-semibold text-white hover:bg-slate-800"
            >
              {copied ? <Check className="mr-1.5 h-3.5 w-3.5" /> : <Copy className="mr-1.5 h-3.5 w-3.5" />}
              {copied ? "Copied" : "Copy Code"}
            </Button>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}
