-- Durable product roadmap and atomic, per-output credit reservations.

create table if not exists public.project_screen_roadmap (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  parent_item_id uuid null references public.project_screen_roadmap(id) on delete cascade,
  generated_screen_id uuid null references public.screens(id) on delete set null,
  stable_key text not null,
  kind text not null check (kind in ('screen', 'state')),
  screen_type text null check (screen_type is null or screen_type in ('root', 'detail')),
  name text not null check (char_length(name) between 1 and 100),
  description text not null default '',
  priority text not null default 'recommended' check (priority in ('core', 'required', 'recommended', 'optional')),
  status text not null default 'planned' check (status in ('planned', 'queued', 'building', 'ready', 'failed', 'dismissed')),
  source text not null default 'planner' check (source in ('prompt', 'planner', 'navigation', 'existing')),
  explicitly_requested boolean not null default false,
  sequence integer not null default 0,
  tranche integer not null default 1 check (tranche >= 1),
  dependency_keys text[] not null default '{}',
  state_key text null,
  state_label text null,
  state_role text null,
  trigger_label text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (project_id, stable_key)
);

create index if not exists project_screen_roadmap_project_sequence_idx
  on public.project_screen_roadmap(project_id, tranche, sequence);
create index if not exists project_screen_roadmap_project_status_idx
  on public.project_screen_roadmap(project_id, status, priority);
create index if not exists project_screen_roadmap_parent_idx
  on public.project_screen_roadmap(parent_item_id)
  where parent_item_id is not null;
create unique index if not exists project_screen_roadmap_generated_screen_idx
  on public.project_screen_roadmap(generated_screen_id)
  where generated_screen_id is not null;

alter table public.screens
  add column if not exists roadmap_item_id uuid null references public.project_screen_roadmap(id) on delete set null;

create unique index if not exists screens_roadmap_item_unique_idx
  on public.screens(roadmap_item_id)
  where roadmap_item_id is not null;

alter table public.generation_runs
  add column if not exists client_request_id uuid null;

create unique index if not exists generation_runs_owner_client_request_unique_idx
  on public.generation_runs(owner_id, client_request_id)
  where client_request_id is not null;

create table if not exists public.credits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  credits numeric(10, 2) not null default 0,
  user_id uuid not null references auth.users(id) on delete cascade
);
create index if not exists credits_user_id_idx on public.credits(user_id);
alter table public.credits enable row level security;
drop policy if exists "Users can view their own credits" on public.credits;
create policy "Users can view their own credits"
  on public.credits for select
  using (auth.uid() = user_id);
drop policy if exists "Users can initialize zero credits" on public.credits;
create policy "Users can initialize zero credits"
  on public.credits for insert
  with check (auth.uid() = user_id and credits = 0);

-- The legacy table did not enforce the one-balance-row invariant used by the service.
with balances as (
  select user_id, min(id) as keep_id, sum(credits) as total_credits
  from public.credits
  group by user_id
  having count(*) > 1
), updated as (
  update public.credits as credit
  set credits = balances.total_credits
  from balances
  where credit.id = balances.keep_id
  returning credit.user_id, credit.id
)
delete from public.credits as duplicate
using updated
where duplicate.user_id = updated.user_id
  and duplicate.id <> updated.id;

create unique index if not exists credits_user_id_unique_idx on public.credits(user_id);

create table if not exists public.credit_reservations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  project_id uuid null references public.projects(id) on delete cascade,
  generation_run_id uuid null references public.generation_runs(id) on delete cascade,
  roadmap_item_id uuid null references public.project_screen_roadmap(id) on delete set null,
  screen_id uuid null references public.screens(id) on delete set null,
  output_key text not null,
  output_kind text not null check (output_kind in ('screen', 'state', 'edit')),
  amount numeric(10, 2) not null check (amount > 0),
  status text not null default 'reserved' check (status in ('reserved', 'captured', 'released')),
  release_reason text null,
  expires_at timestamptz not null default (timezone('utc', now()) + interval '45 minutes'),
  reserved_at timestamptz not null default timezone('utc', now()),
  settled_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (owner_id, output_key)
);

create index if not exists credit_reservations_run_idx
  on public.credit_reservations(generation_run_id, status);
create index if not exists credit_reservations_stale_idx
  on public.credit_reservations(status, expires_at)
  where status = 'reserved';
create index if not exists credit_reservations_screen_idx
  on public.credit_reservations(screen_id)
  where screen_id is not null;

alter table public.project_screen_roadmap enable row level security;
alter table public.credit_reservations enable row level security;

drop policy if exists "Users can view their own project roadmap" on public.project_screen_roadmap;
create policy "Users can view their own project roadmap"
  on public.project_screen_roadmap for select
  using (auth.uid() = owner_id);

drop policy if exists "Users can view their own credit reservations" on public.credit_reservations;
create policy "Users can view their own credit reservations"
  on public.credit_reservations for select
  using (auth.uid() = owner_id);

-- Existing canvases become ready roadmap items without changing their IDs or hierarchy.
insert into public.project_screen_roadmap (
  project_id, owner_id, generated_screen_id, stable_key, kind, screen_type,
  name, description, priority, status, source, sequence, state_key, state_label, state_role
)
select
  screen.project_id,
  screen.owner_id,
  screen.id,
  'existing-screen-' || screen.id::text,
  'screen',
  case when screen.parent_screen_id is null then 'root' else 'detail' end,
  screen.name,
  screen.prompt,
  'core',
  case when screen.status = 'ready' then 'ready' when screen.status = 'failed' then 'failed' else 'building' end,
  'existing',
  screen.sort_index,
  screen.state_key,
  screen.state_label,
  screen.state_role
from public.screens as screen
where screen.parent_screen_id is null
on conflict (project_id, stable_key) do nothing;

insert into public.project_screen_roadmap (
  project_id, owner_id, parent_item_id, generated_screen_id, stable_key, kind,
  name, description, priority, status, source, sequence, state_key, state_label, state_role
)
select
  child.project_id,
  child.owner_id,
  parent_item.id,
  child.id,
  'existing-state-' || child.id::text,
  'state',
  child.name,
  child.prompt,
  'recommended',
  case when child.status = 'ready' then 'ready' when child.status = 'failed' then 'failed' else 'building' end,
  'existing',
  child.sort_index,
  coalesce(child.state_key, 'state-' || child.id::text),
  child.state_label,
  child.state_role
from public.screens as child
join public.project_screen_roadmap as parent_item
  on parent_item.generated_screen_id = child.parent_screen_id
where child.parent_screen_id is not null
on conflict (project_id, stable_key) do nothing;

update public.screens as screen
set roadmap_item_id = item.id
from public.project_screen_roadmap as item
where item.generated_screen_id = screen.id
  and screen.roadmap_item_id is null;

create or replace function public.reserve_generation_credits(
  input_owner_id uuid,
  input_project_id uuid,
  input_generation_run_id uuid,
  input_outputs jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  output_count integer;
  existing_count integer;
  requested_total numeric(10, 2);
  existing_total numeric(10, 2);
  available_balance numeric(10, 2);
  requested_keys text[];
  existing_keys text[];
begin
  if jsonb_typeof(input_outputs) <> 'array' or jsonb_array_length(input_outputs) = 0 then
    raise exception 'At least one credit reservation output is required.' using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.generation_runs
    where id = input_generation_run_id
      and project_id = input_project_id
      and owner_id = input_owner_id
  ) then
    raise exception 'Generation run ownership mismatch.' using errcode = '42501';
  end if;

  select count(*), coalesce(sum((entry ->> 'amount')::numeric), 0),
         array_agg(entry ->> 'outputKey' order by entry ->> 'outputKey')
  into output_count, requested_total, requested_keys
  from jsonb_array_elements(input_outputs) as entry;

  if output_count > 8 or requested_total <= 0 then
    raise exception 'Invalid credit reservation batch.' using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(input_outputs) as entry
    where nullif(btrim(entry ->> 'outputKey'), '') is null
      or entry ->> 'outputKind' is null
      or entry ->> 'outputKind' not in ('screen', 'state', 'edit')
      or entry ->> 'amount' is null
      or (entry ->> 'amount')::numeric <= 0
  ) then
    raise exception 'Credit reservation manifest contains an invalid output.' using errcode = '22023';
  end if;
  if output_count <> (
    select count(distinct entry ->> 'outputKey')
    from jsonb_array_elements(input_outputs) as entry
  ) then
    raise exception 'Credit reservation output keys must be unique.' using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(input_outputs) as entry
    where nullif(entry ->> 'roadmapItemId', '') is not null
      and not exists (
        select 1
        from public.project_screen_roadmap as item
        where item.id = (entry ->> 'roadmapItemId')::uuid
          and item.project_id = input_project_id
          and item.owner_id = input_owner_id
      )
  ) then
    raise exception 'Roadmap reservation ownership mismatch.' using errcode = '42501';
  end if;

  select count(*), coalesce(sum(amount), 0), array_agg(output_key order by output_key)
  into existing_count, existing_total, existing_keys
  from public.credit_reservations
  where generation_run_id = input_generation_run_id;

  if existing_count > 0 then
    if existing_count <> output_count
      or existing_total <> requested_total
      or existing_keys is distinct from requested_keys then
      raise exception 'Generation run already has a different reservation manifest.' using errcode = '23505';
    end if;
    return jsonb_build_object(
      'reservedCredits', existing_total,
      'outputCount', existing_count,
      'idempotent', true,
      'availableBalance', (select credits from public.credits where user_id = input_owner_id)
    );
  end if;

  insert into public.credits(user_id, credits)
  values (input_owner_id, 0)
  on conflict (user_id) do nothing;

  select credits into available_balance
  from public.credits
  where user_id = input_owner_id
  for update;

  if available_balance < requested_total then
    raise exception 'Insufficient credits. Available: %, Required: %', available_balance, requested_total
      using errcode = 'P0001';
  end if;

  update public.credits
  set credits = credits - requested_total
  where user_id = input_owner_id;

  insert into public.credit_reservations (
    owner_id, project_id, generation_run_id, roadmap_item_id,
    output_key, output_kind, amount, metadata
  )
  select
    input_owner_id,
    input_project_id,
    input_generation_run_id,
    nullif(entry ->> 'roadmapItemId', '')::uuid,
    entry ->> 'outputKey',
    entry ->> 'outputKind',
    (entry ->> 'amount')::numeric,
    coalesce(entry -> 'metadata', '{}'::jsonb)
  from jsonb_array_elements(input_outputs) as entry;

  return jsonb_build_object(
    'reservedCredits', requested_total,
    'outputCount', output_count,
    'idempotent', false,
    'availableBalance', available_balance - requested_total
  );
end;
$$;

create or replace function public.capture_generation_credit(
  input_owner_id uuid,
  input_generation_run_id uuid,
  input_output_key text,
  input_screen_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  reservation_status text;
begin
  select status into reservation_status
  from public.credit_reservations
  where owner_id = input_owner_id
    and generation_run_id = input_generation_run_id
    and output_key = input_output_key
  for update;

  if not found then
    raise exception 'Credit reservation not found.' using errcode = 'P0002';
  end if;
  if reservation_status = 'captured' then
    return false;
  end if;
  if reservation_status = 'released' then
    raise exception 'Released credit reservation cannot be captured.' using errcode = '55000';
  end if;

  update public.credit_reservations
  set status = 'captured', screen_id = coalesce(input_screen_id, screen_id),
      settled_at = timezone('utc', now()), updated_at = timezone('utc', now())
  where owner_id = input_owner_id
    and generation_run_id = input_generation_run_id
    and output_key = input_output_key;
  return true;
end;
$$;

create or replace function public.release_generation_credit(
  input_owner_id uuid,
  input_generation_run_id uuid,
  input_output_key text,
  input_reason text default null
)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare
  reservation_amount numeric(10, 2);
  reservation_status text;
begin
  select amount, status into reservation_amount, reservation_status
  from public.credit_reservations
  where owner_id = input_owner_id
    and generation_run_id = input_generation_run_id
    and output_key = input_output_key
  for update;

  if not found or reservation_status <> 'reserved' then
    return 0;
  end if;

  update public.credits
  set credits = credits + reservation_amount
  where user_id = input_owner_id;

  update public.credit_reservations
  set status = 'released', release_reason = left(input_reason, 500),
      settled_at = timezone('utc', now()), updated_at = timezone('utc', now())
  where owner_id = input_owner_id
    and generation_run_id = input_generation_run_id
    and output_key = input_output_key;
  return reservation_amount;
end;
$$;

create or replace function public.release_generation_credit_remainder(
  input_owner_id uuid,
  input_generation_run_id uuid,
  input_reason text default null
)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare
  released_total numeric(10, 2);
begin
  -- A screen can be durably saved even if the worker loses its connection
  -- before the explicit capture RPC returns. Settle those outputs first so
  -- terminal cleanup never refunds a successfully delivered screen.
  update public.credit_reservations as reservation
  set status = 'captured', settled_at = timezone('utc', now()),
      updated_at = timezone('utc', now())
  from public.screens as screen
  where reservation.owner_id = input_owner_id
    and reservation.generation_run_id = input_generation_run_id
    and reservation.status = 'reserved'
    and reservation.screen_id = screen.id
    and screen.status = 'ready';

  perform 1
  from public.credit_reservations
  where owner_id = input_owner_id
    and generation_run_id = input_generation_run_id
    and status = 'reserved'
  for update;

  select coalesce(sum(amount), 0) into released_total
  from public.credit_reservations
  where owner_id = input_owner_id
    and generation_run_id = input_generation_run_id
    and status = 'reserved';

  if released_total <= 0 then
    return 0;
  end if;

  update public.credits
  set credits = credits + released_total
  where user_id = input_owner_id;

  update public.credit_reservations
  set status = 'released', release_reason = left(input_reason, 500),
      settled_at = timezone('utc', now()), updated_at = timezone('utc', now())
  where owner_id = input_owner_id
    and generation_run_id = input_generation_run_id
    and status = 'reserved';
  return released_total;
end;
$$;

create or replace function public.adjust_user_credits(
  input_user_id uuid,
  input_delta numeric
)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare
  current_balance numeric(10, 2);
  next_balance numeric(10, 2);
begin
  if input_delta = 0 then
    raise exception 'Credit adjustment must be non-zero.' using errcode = '22023';
  end if;

  if auth.role() <> 'service_role' and auth.uid() is distinct from input_user_id then
    raise exception 'Credit adjustment ownership mismatch.' using errcode = '42501';
  end if;
  if auth.role() <> 'service_role' and input_delta > 0 then
    raise exception 'Only the service role may add credits.' using errcode = '42501';
  end if;

  insert into public.credits(user_id, credits)
  values (input_user_id, 0)
  on conflict (user_id) do nothing;

  select credits into current_balance
  from public.credits
  where user_id = input_user_id
  for update;

  next_balance := current_balance + input_delta;
  if next_balance < 0 then
    raise exception 'Insufficient credits. Available: %, Required: %', current_balance, abs(input_delta)
      using errcode = 'P0001';
  end if;

  update public.credits set credits = next_balance where user_id = input_user_id;
  return next_balance;
end;
$$;

create or replace function public.set_user_credits_atomic(
  input_user_id uuid,
  input_balance numeric
)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
begin
  if input_balance < 0 then
    raise exception 'Credit balance cannot be negative.' using errcode = '22023';
  end if;

  insert into public.credits(user_id, credits)
  values (input_user_id, input_balance)
  on conflict (user_id) do update set credits = excluded.credits;
  return input_balance;
end;
$$;

revoke all on function public.reserve_generation_credits(uuid, uuid, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.capture_generation_credit(uuid, uuid, text, uuid) from public, anon, authenticated;
revoke all on function public.release_generation_credit(uuid, uuid, text, text) from public, anon, authenticated;
revoke all on function public.release_generation_credit_remainder(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.adjust_user_credits(uuid, numeric) from public, anon, authenticated;
revoke all on function public.set_user_credits_atomic(uuid, numeric) from public, anon, authenticated;
grant execute on function public.reserve_generation_credits(uuid, uuid, uuid, jsonb) to service_role;
grant execute on function public.capture_generation_credit(uuid, uuid, text, uuid) to service_role;
grant execute on function public.release_generation_credit(uuid, uuid, text, text) to service_role;
grant execute on function public.release_generation_credit_remainder(uuid, uuid, text) to service_role;
grant execute on function public.adjust_user_credits(uuid, numeric) to service_role;
grant execute on function public.adjust_user_credits(uuid, numeric) to authenticated;
grant execute on function public.set_user_credits_atomic(uuid, numeric) to service_role;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'credits'
  ) then
    alter publication supabase_realtime add table public.credits;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'project_screen_roadmap'
  ) then
    alter publication supabase_realtime add table public.project_screen_roadmap;
  end if;
end;
$$;

create or replace function public.dismiss_deleted_screen_roadmap_item()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.project_screen_roadmap
  set generated_screen_id = null, status = 'dismissed', updated_at = timezone('utc', now())
  where generated_screen_id = old.id;
  return old;
end;
$$;

drop trigger if exists dismiss_screen_roadmap_item_before_delete on public.screens;
create trigger dismiss_screen_roadmap_item_before_delete
before delete on public.screens
for each row execute function public.dismiss_deleted_screen_roadmap_item();

create trigger set_project_screen_roadmap_updated_at
before update on public.project_screen_roadmap
for each row execute function public.handle_updated_at();

create trigger set_credit_reservations_updated_at
before update on public.credit_reservations
for each row execute function public.handle_updated_at();
