-- Launch credit codes.
-- A code grants a fixed number of credits and can be redeemed a set number of times.
-- A person redeems at most one code per campaign, so fifty single-use launch links
-- reach fifty people and nobody collects several. Only the service role reads codes.
-- Apply this before deploying the code that calls redeem_credit_code.

create table if not exists public.credit_codes (
  code text primary key,
  campaign text not null,
  credits numeric(10, 2) not null,
  max_redemptions integer not null default 1,
  redemption_count integer not null default 0,
  expires_at timestamptz null,
  disabled_at timestamptz null,
  note text null,
  created_at timestamptz not null default now(),
  constraint credit_codes_code_format check (code ~ '^[A-Z0-9][A-Z0-9-]{3,39}$'),
  constraint credit_codes_campaign_format check (campaign ~ '^[a-z0-9][a-z0-9-]{0,63}$'),
  constraint credit_codes_credits_range check (credits > 0 and credits <= 10000),
  constraint credit_codes_redemptions_range check (
    max_redemptions > 0 and redemption_count between 0 and max_redemptions
  )
);

create index if not exists credit_codes_campaign_idx on public.credit_codes(campaign);

create table if not exists public.credit_code_redemptions (
  id bigint generated by default as identity primary key,
  code text not null references public.credit_codes(code) on delete restrict,
  campaign text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  credits numeric(10, 2) not null,
  created_at timestamptz not null default now(),
  constraint credit_code_redemptions_one_per_campaign unique (campaign, user_id)
);

create index if not exists credit_code_redemptions_code_idx on public.credit_code_redemptions(code);

-- No policies: only the service role, which bypasses RLS, reads or writes codes.
alter table public.credit_codes enable row level security;
alter table public.credit_code_redemptions enable row level security;
revoke all on public.credit_codes from anon, authenticated;
revoke all on public.credit_code_redemptions from anon, authenticated;

-- Returns { status } where status is redeemed, already_redeemed, expired, exhausted or
-- not_found. A redeemed result also carries the credits granted and the new balance.
create or replace function public.redeem_credit_code(
  input_user_id uuid,
  input_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(btrim(coalesce(input_code, '')));
  v_row public.credit_codes%rowtype;
  v_balance numeric(10, 2);
begin
  if input_user_id is null then
    raise exception 'Credit code redemption needs a user.' using errcode = '22023';
  end if;

  if v_code !~ '^[A-Z0-9][A-Z0-9-]{3,39}$' then
    return jsonb_build_object('status', 'not_found');
  end if;

  -- The code row lock serialises redemptions of one code, so its cap holds in a rush.
  select * into v_row
  from public.credit_codes
  where code = v_code
  for update;

  if not found or v_row.disabled_at is not null then
    return jsonb_build_object('status', 'not_found');
  end if;

  -- Checked before expiry and the cap: someone who already claimed should hear that.
  if exists (
    select 1 from public.credit_code_redemptions
    where campaign = v_row.campaign and user_id = input_user_id
  ) then
    return jsonb_build_object('status', 'already_redeemed');
  end if;

  if v_row.expires_at is not null and v_row.expires_at <= now() then
    return jsonb_build_object('status', 'expired');
  end if;

  if v_row.redemption_count >= v_row.max_redemptions then
    return jsonb_build_object('status', 'exhausted');
  end if;

  begin
    insert into public.credit_code_redemptions(code, campaign, user_id, credits)
    values (v_code, v_row.campaign, input_user_id, v_row.credits);
  exception when unique_violation then
    -- Two codes from one campaign redeemed at once by the same person: one wins.
    return jsonb_build_object('status', 'already_redeemed');
  end;

  update public.credit_codes
  set redemption_count = redemption_count + 1
  where code = v_code;

  insert into public.credits(user_id, credits)
  values (input_user_id, 0)
  on conflict (user_id) do nothing;

  update public.credits
  set credits = credits + v_row.credits
  where user_id = input_user_id
  returning credits into v_balance;

  return jsonb_build_object(
    'status', 'redeemed',
    'credits', v_row.credits,
    'balance', v_balance
  );
end;
$$;

revoke all on function public.redeem_credit_code(uuid, text) from public, anon, authenticated;
grant execute on function public.redeem_credit_code(uuid, text) to service_role;
