import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import {
  curatedShowcaseScreenCount,
  landingShowcaseCollections,
} from "@/lib/showcase";

export default function AppShowcase() {
  return (
    <section id="showcase" className="relative overflow-hidden bg-[#FAFAFA] pb-14">
      <div className="relative overflow-hidden bg-[radial-gradient(circle_at_50%_-20%,#222_0%,#080808_48%,#000_76%)] pb-32 pt-20 text-white sm:pb-40 sm:pt-28">
        <div aria-hidden="true" className="pointer-events-none absolute inset-x-0 bottom-0 h-32 bg-gradient-to-b from-transparent to-black/50" />
        <div className="relative mx-auto max-w-[1200px] px-4 sm:px-6">
          <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-end">
            <div>
              <div className="mb-5 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.16em] text-white/45">
                <span className="h-1.5 w-1.5 rounded-full bg-[#1b7fcc]" />
                Generated by Drawgle
              </div>
              <h2 className="max-w-[880px] font-pixel-square text-[36px] font-semibold leading-[1.03] tracking-tight sm:text-5xl md:text-[54px] xl:text-[60px]">
                One idea is not
                <br />
                <span className="text-white/45">limited to one visual language.</span>
              </h2>
            </div>

            <div>
              <p className="max-w-md text-sm leading-6 text-white/55 sm:text-base">
                Four original app directions, shown side by side. Explore all{" "}
                {curatedShowcaseScreenCount} curated screens in the interactive gallery.
              </p>
              <Link
                href="/showcase"
                className="group mt-5 inline-flex items-center gap-2 text-sm font-semibold text-white transition-opacity hover:opacity-75"
              >
                Explore all screens
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
              </Link>
            </div>
          </div>
        </div>
      </div>

      <div className="relative z-10 -mt-20 px-3 sm:-mt-24 sm:px-5">
        <div className="mx-auto max-w-[1320px] rounded-[26px] border border-black/[0.08] bg-[#efefec] p-1.5 sm:rounded-[32px] sm:p-2">
          <div className="grid overflow-hidden rounded-[20px] border border-white/80 bg-[#f8f8f6] sm:rounded-[25px] lg:grid-cols-2">
            {landingShowcaseCollections.map((collection, collectionIndex) => (
              <article
                key={collection.id}
                className={`relative min-w-0 px-4 py-6 sm:px-7 sm:py-8 ${
                  collectionIndex < 2 ? "border-b border-black/[0.07]" : ""
                } ${collectionIndex % 2 === 0 ? "lg:border-r lg:border-black/[0.07]" : ""} ${
                  collectionIndex === 1 ? "border-b border-black/[0.07] lg:border-b" : ""
                }`}
                style={{
                  backgroundImage: `radial-gradient(circle at 15% 10%, ${collection.palette[3]}22, transparent 34%)`,
                }}
              >
                <div className="mb-5 flex items-end justify-between gap-4">
                  <div>
                    <div className="text-[9px] font-semibold uppercase tracking-[0.14em] text-[#1b7fcc]">
                      Direction {String(collectionIndex + 1).padStart(2, "0")}
                    </div>
                    <h3 className="mt-1 text-lg font-semibold tracking-tight text-black sm:text-xl">
                      {collection.name}
                    </h3>
                  </div>
                  <p className="hidden max-w-[230px] text-right text-[11px] leading-4 text-black/40 sm:block">
                    {collection.description}
                  </p>
                </div>

                <div className="grid grid-cols-3 items-start gap-[clamp(5px,1.4vw,18px)]">
                  {collection.screens.map((screen, screenIndex) => (
                    <div key={screen.src} className="min-w-0">
                      <div className="relative aspect-[390/844] overflow-hidden rounded-[clamp(9px,1.7vw,22px)] border border-black/[0.12] bg-white shadow-[0_20px_45px_-38px_rgba(0,0,0,0.55)]">
                        <Image
                          src={screen.screenshot}
                          alt={`${collection.name} ${screen.label} mobile UI generated by Drawgle`}
                          fill
                          priority={collectionIndex < 2}
                          sizes="(max-width: 1023px) 30vw, 190px"
                          className="object-cover"
                        />
                      </div>
                      <div className="mt-2 truncate text-center text-[8px] font-semibold text-black/65 sm:text-[10px]">
                        {screen.label}
                        <span className="ml-1 hidden font-normal text-black/35 sm:inline">{screen.role}</span>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-5 flex items-center justify-between border-t border-black/[0.07] pt-4">
                  <span className="text-[10px] text-black/40">Three original mobile screens</span>
                  <Link
                    href={`/project/new?prompt=${encodeURIComponent(collection.prompt)}`}
                    className="group inline-flex items-center gap-1.5 text-[10px] font-semibold text-[#1b7fcc] sm:text-[11px]"
                  >
                    Design like this
                    <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
                  </Link>
                </div>
              </article>
            ))}
          </div>

          <div className="flex flex-col items-center justify-between gap-4 px-5 py-5 sm:flex-row sm:px-7">
            <p className="text-center text-xs leading-5 text-black/45 sm:text-left sm:text-sm">
              See every direction rendered live and interact with the original screens.
            </p>
            <Link
              href="/showcase"
              className="group flex min-h-11 shrink-0 items-center justify-center gap-3 rounded-[9px] border border-[#1b7fcc]/35 bg-[#1b7fcc] px-5 text-sm font-semibold text-white shadow-[inset_0_1px_0_rgba(255,255,255,0.18),inset_0_-2px_3px_rgba(0,0,0,0.24)] transition-colors hover:bg-[#1975bd]"
            >
              Explore the full showcase
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
