/*
 * AppTheme.kt
 * Drawgle Auto-generated
 */

package com.drawgle.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object AppTheme {
    val BackgroundPrimary = Color(0xFFFFFFFF)
    val BackgroundSecondary = Color(0xFFF3F4F6)
    val SurfaceCard = Color(0xFFFFFFFF)
    val ActionPrimary = Color(0xFF3B82F6)
    val ActionOnPrimary = Color(0xFFFFFFFF)
    val TextHigh = Color(0xFF111827)
    val TextMedium = Color(0xFF4B5563)
    val TextLow = Color(0xFF9CA3AF)
    val BorderDivider = Color(0xFFE5E7EB)
    
    val BorderRadiusApp = 18.dp
    val BorderRadiusPill = 9999.dp
}

/*
 * HomeScreen.kt
 * Auto-generated by Drawgle
 */

package com.drawgle.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import com.drawgle.theme.AppTheme

@Composable
fun HomeScreen() {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(AppTheme.BackgroundPrimary)
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
        ) {
    Column(
        modifier = Modifier
        horizontalAlignment = Alignment.Start,
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .background(Color(0xFF0F0F0F))
            horizontalAlignment = Alignment.Start,
        ) {
            Column(
                modifier = Modifier
                horizontalAlignment = Alignment.CenterHorizontally,
            ) {
                Column(
                    modifier = Modifier
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Column(
                        modifier = Modifier
                            .width(32.dp)
                            .height(32.dp)
                            .clip(RoundedCornerShape(9999.dp))
                        horizontalAlignment = Alignment.Start,
                    ) {
                        AsyncImage(
                            model = "https://pub-7c8c3c7444724a39ba3eeb8accbbca4a.r2.dev/visual-assets/60ae5021-d010-4997-839a-7198a052762d/display_1024.png",
                            contentDescription = null,
                            modifier = Modifier
                                .fillMaxWidth()
                        )
                    }
                    Column(
                        modifier = Modifier
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Text(
                            text = "James",
                            fontSize = 14.sp,
                            color = Color(0xFFFFFFFF),
                            fontWeight = FontWeight.Bold,
                        
                        )
                        Text(
                            text = "Figueroa",
                            fontSize = 14.sp,
                            color = Color(0xFFA1A1A1),
                        
                        )
                    }
                }
                Column(
                    modifier = Modifier
                        .background(Color(0xFF212124))
                    horizontalAlignment = Alignment.End,
                ) {
                    Column(
                        modifier = Modifier
                            .width(36.dp)
                            .height(36.dp)
                            .background(Color(0xFF000000))
                            .clip(RoundedCornerShape(9999.dp))
                        horizontalAlignment = Alignment.CenterHorizontally,
                    ) {
                        Column(
                            modifier = Modifier
                                .width(18.dp)
                                .height(18.dp)
                            horizontalAlignment = Alignment.Start,
                        ) {
                        }
                    }
                    Column(
                        modifier = Modifier
                            .background(Color(0xFFFFFFFF))
                            .clip(RoundedCornerShape(12.dp))
                        horizontalAlignment = Alignment.CenterHorizontally,
                    ) {
                        Text(
                            text = "6",
                            fontSize = 14.sp,
                            color = Color(0xFF000000),
                            fontWeight = FontWeight.Bold,
                        
                        )
                        Text(
                            text = "products",
                            fontSize = 14.sp,
                            color = Color(0xFF000000),
                        
                        )
                    }
                }
            }
            Column(
                modifier = Modifier
                horizontalAlignment = Alignment.Start,
            ) {
                Column(
                    modifier = Modifier
                    horizontalAlignment = Alignment.Start,
                ) {
                    Text(
                        text = "Cookies",
                        fontSize = 24.sp,
                        color = Color(0xFFFFFFFF),
                        fontWeight = FontWeight.Bold,
                    
                    )
                    Text(
                        text = "Premium",
                        fontSize = 24.sp,
                        color = Color(0xFFE88D48),
                        fontWeight = FontWeight.Bold,
                    
                    )
                }
                Column(
                    modifier = Modifier
                    horizontalAlignment = Alignment.Start,
                ) {
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF#FFFFFF)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(4.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(text = "See more")
                        }
                    }
                }
            }
            Column(
                modifier = Modifier
                horizontalAlignment = Alignment.Start,
            ) {
                Column(
                    modifier = Modifier
                        .padding(start = 0.dp, top = 0.dp, end = 0.dp, bottom = 16.dp)
                    horizontalAlignment = Alignment.Start,
                ) {
                    Column(
                        modifier = Modifier
                            .width(160.dp)
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Column(
                            modifier = Modifier
                                .width(100.dp)
                                .height(100.dp)
                            horizontalAlignment = Alignment.Start,
                        ) {
                            AsyncImage(
                                model = "https://pub-7c8c3c7444724a39ba3eeb8accbbca4a.r2.dev/visual-assets/60ae5021-d010-4997-839a-7198a052762d/display_1024.png",
                                contentDescription = null,
                                modifier = Modifier
                                    .fillMaxWidth()
                            )
                        }
                        Column(
                            modifier = Modifier
                                .background(Color(0xFF212124))
                                .clip(RoundedCornerShape(28.dp))
                            horizontalAlignment = Alignment.Start,
                        ) {
                            Text(
                                text = "Chocolate chips",
                                fontSize = 14.sp,
                                color = Color(0xFFFFFFFF),
                                modifier = Modifier
                                    .padding(top = 0.dp, bottom = 4.dp)
                            )
                            Column(
                                modifier = Modifier
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(4.dp),
                            ) {
                                Column(
                                    modifier = Modifier
                                        .width(10.dp)
                                        .height(10.dp)
                                    horizontalAlignment = Alignment.Start,
                                ) {
                                }
                                Text(
                                    text = "Premium",
                                    fontSize = 14.sp,
                                    color = Color(0xFFE88D48),
                                    fontWeight = FontWeight.Bold,
                                
                                )
                            }
                            Column(
                                modifier = Modifier
                                horizontalAlignment = Alignment.CenterHorizontally,
                            ) {
                                Text(
                                    text = "20 USD",
                                    fontSize = 14.sp,
                                    color = Color(0xFF111827),
                                    fontWeight = FontWeight.Bold,
                                
                                )
                                Button(
                                    onClick = { /* Action */ },
                                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF000000)),
                                    shape = RoundedCornerShape(9999.dp),
                                    modifier = Modifier
                                ) {
                                    Row(
                                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Column(
                                            modifier = Modifier
                                                .width(14.dp)
                                                .height(14.dp)
                                            horizontalAlignment = Alignment.Start,
                                        ) {
                                        }
                                    }
                                }
                            }
                        }
                    }
                    Column(
                        modifier = Modifier
                            .width(160.dp)
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Column(
                            modifier = Modifier
                                .width(100.dp)
                                .height(100.dp)
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Column(
                                modifier = Modifier
                                    .width(80.dp)
                                    .height(80.dp)
                                    .background(Color(0xFF3A2A1D))
                                    .clip(RoundedCornerShape(9999.dp))
                                horizontalAlignment = Alignment.CenterHorizontally,
                            ) {
                                Column(
                                    modifier = Modifier
                                        .width(32.dp)
                                        .height(32.dp)
                                    horizontalAlignment = Alignment.Start,
                                ) {
                                }
                            }
                        }
                        Column(
                            modifier = Modifier
                                .background(Color(0xFF212124))
                                .clip(RoundedCornerShape(28.dp))
                            horizontalAlignment = Alignment.Start,
                        ) {
                            Text(
                                text = "Oatmeal with raisins",
                                fontSize = 14.sp,
                                color = Color(0xFFFFFFFF),
                                modifier = Modifier
                                    .padding(top = 0.dp, bottom = 4.dp)
                            )
                            Column(
                                modifier = Modifier
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(4.dp),
                            ) {
                                Column(
                                    modifier = Modifier
                                        .width(10.dp)
                                        .height(10.dp)
                                    horizontalAlignment = Alignment.Start,
                                ) {
                                }
                                Text(
                                    text = "Premium",
                                    fontSize = 14.sp,
                                    color = Color(0xFFE88D48),
                                    fontWeight = FontWeight.Bold,
                                
                                )
                            }
                            Column(
                                modifier = Modifier
                                horizontalAlignment = Alignment.CenterHorizontally,
                            ) {
                                Text(
                                    text = "16 USD",
                                    fontSize = 14.sp,
                                    color = Color(0xFF111827),
                                    fontWeight = FontWeight.Bold,
                                
                                )
                                Button(
                                    onClick = { /* Action */ },
                                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF000000)),
                                    shape = RoundedCornerShape(9999.dp),
                                    modifier = Modifier
                                ) {
                                    Row(
                                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Column(
                                            modifier = Modifier
                                                .width(14.dp)
                                                .height(14.dp)
                                            horizontalAlignment = Alignment.Start,
                                        ) {
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Column(
                modifier = Modifier
                horizontalAlignment = Alignment.Start,
            ) {
                Column(
                    modifier = Modifier
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Text(
                        text = "Offers",
                        fontSize = 18.sp,
                        color = Color(0xFF111827),
                        fontWeight = FontWeight.Bold,
                    
                    )
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF#FFFFFF)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(text = "See more")
                        }
                    }
                }
                Column(
                    modifier = Modifier
                        .background(Color(0xFF212124))
                        .clip(RoundedCornerShape(28.dp))
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Column(
                        modifier = Modifier
                            .width(80.dp)
                            .height(80.dp)
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(Color(0xFF1A1A1A))
                                .clip(RoundedCornerShape(20.dp))
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            AsyncImage(
                                model = "https://pub-7c8c3c7444724a39ba3eeb8accbbca4a.r2.dev/visual-assets/60ae5021-d010-4997-839a-7198a052762d/display_1024.png",
                                contentDescription = null,
                                modifier = Modifier
                            )
                        }
                    }
                    Column(
                        modifier = Modifier
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Text(
                            text = "Double chocolate",
                            fontSize = 14.sp,
                            color = Color(0xFFFFFFFF),
                        
                        )
                        Column(
                            modifier = Modifier
                            horizontalAlignment = Alignment.CenterHorizontally,
                            verticalArrangement = Arrangement.spacedBy(4.dp),
                        ) {
                            Column(
                                modifier = Modifier
                                    .width(10.dp)
                                    .height(10.dp)
                                horizontalAlignment = Alignment.Start,
                            ) {
                            }
                            Text(
                                text = "Premium",
                                fontSize = 14.sp,
                                color = Color(0xFFE88D48),
                                fontWeight = FontWeight.Bold,
                            
                            )
                        }
                        Column(
                            modifier = Modifier
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.spacedBy(8.dp),
                        ) {
                            Text(
                                text = "12 USD",
                                fontSize = 14.sp,
                                color = Color(0xFFFFFFFF),
                                fontWeight = FontWeight.Bold,
                            
                            )
                            Text(
                                text = "20 USD",
                                fontSize = 14.sp,
                                color = Color(0xFF666666),
                            
                            )
                        }
                    }
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF000000)),
                        shape = RoundedCornerShape(9999.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column(
                                modifier = Modifier
                                    .width(18.dp)
                                    .height(18.dp)
                                horizontalAlignment = Alignment.Start,
                            ) {
                            }
                        }
                    }
                }
            }
            Column(
                modifier = Modifier
                horizontalAlignment = Alignment.Start,
            ) {
            }
        }
        Column(
            modifier = Modifier
            horizontalAlignment = Alignment.Start,
        ) {
            Column(
                modifier = Modifier
                horizontalAlignment = Alignment.Start,
            ) {
                Column(
                    modifier = Modifier
                    horizontalAlignment = Alignment.Start,
                ) {
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF#FFFFFF)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column(
                                modifier = Modifier
                                horizontalAlignment = Alignment.Start,
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Home,
                                    contentDescription = null,
                                    tint = Color(0xFF111827),
                                    modifier = Modifier.size(14.dp)
                                )
                            }
                            Text(
                                text = "Home",
                                fontSize = 14.sp,
                                color = Color(0xFF111827),
                            
                            )
                        }
                    }
                }
            }
        }
    }
        }
    }
}
