//
// app_theme.dart
// Drawgle Auto-generated
//

import 'package:flutter/material.dart';

class AppTheme {
  static const Color backgroundPrimary = Color(0xFFFFFFFF);
  static const Color backgroundSecondary = Color(0xFFF3F4F6);
  static const Color surfaceCard = Color(0xFFFFFFFF);
  static const Color actionPrimary = Color(0xFF3B82F6);
  static const Color actionOnPrimary = Color(0xFFFFFFFF);
  static const Color textHigh = Color(0xFF111827);
  static const Color textMedium = Color(0xFF4B5563);
  static const Color textLow = Color(0xFF9CA3AF);
  static const Color borderDivider = Color(0xFFE5E7EB);
  
  static const double borderRadiusApp = 18;
  static const double borderRadiusPill = 9999.0;
  
  static const double screenPadding = 24;
  static const double sectionGap = 24;
  static const double elementGap = 16;
}

//
// home_screen.dart
// Auto-generated by Drawgle
//

import 'package:flutter/material.dart';
import 'app_theme.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.backgroundPrimary,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    mainAxisAlignment: MainAxisAlignment.start,
    children: [
    Container(
        decoration: BoxDecoration(
      color: AppTheme.backgroundPrimary,
    ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
        Container(
            height: 64.0,
            padding: EdgeInsets.only(left: AppTheme.screenPadding, top: 0.0, right: AppTheme.screenPadding, bottom: 0.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
            ElevatedButton(
              onPressed: () {},
              style: ElevatedButton.styleFrom(
                backgroundColor: Color(0xFFFFFFFF),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12.0),
                ),
                padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(Icons.arrow_left, size: 14.0, color: Color(0xFF111827))
                ],
              ),
            ),
            Text(
              'Diagnostics',
              style: TextStyle(
                fontSize: 17.0,
                color: AppTheme.textHigh,
                fontWeight: FontWeight.bold,
              ),
            ),
Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
              ElevatedButton(
                onPressed: () {},
                style: ElevatedButton.styleFrom(
                  backgroundColor: Color(0xFFFFFFFF),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12.0),
                  ),
                  padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.file_text, size: 14.0, color: Color(0xFF111827))
                  ],
                ),
              ),
              ElevatedButton(
                onPressed: () {},
                style: ElevatedButton.styleFrom(
                  backgroundColor: Color(0xFFFFFFFF),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12.0),
                  ),
                  padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.filter, size: 14.0, color: Color(0xFF111827))
                  ],
                ),
              )
              ],
            )
            ],
          ),
        ),
        Container(
            padding: EdgeInsets.only(left: AppTheme.screenPadding, top: AppTheme.sectionGap, right: AppTheme.screenPadding, bottom: 96.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
            Container(
                decoration: BoxDecoration(
      color: Color(0xFFE3F2FD),
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp),
    ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                  Text(
                    'Heartbeat',
                    style: TextStyle(
                      fontSize: 12.0,
                      color: AppTheme.textHigh,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                    Text(
                      '82',
                      style: TextStyle(
                        fontSize: 32.0,
                        color: AppTheme.textHigh,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    SizedBox(height: 4.0),
                    Text(
                      'bpm',
                      style: TextStyle(
                        fontSize: 16.0,
                        color: AppTheme.textHigh,
                      ),
                    )
                    ],
                  )
                  ],
                ),
                Container(
                    height: 120.0,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
Column(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                      Icon(Icons.star, size: 14.0, color: Color(0xFF111827))
                      ],
                    )
                    ],
                  ),
                )
                ],
              ),
            ),
            SizedBox(height: AppTheme.sectionGap),
            Container(
                decoration: BoxDecoration(
      color: Color(0xFFFFFFFF),
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp),
    ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                  Text(
                    'R-R Interval',
                    style: TextStyle(
                      fontSize: 12.0,
                      color: AppTheme.textHigh,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                    Text(
                      '851',
                      style: TextStyle(
                        fontSize: 32.0,
                        color: AppTheme.textHigh,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    SizedBox(height: 4.0),
                    Text(
                      'ms',
                      style: TextStyle(
                        fontSize: 16.0,
                        color: AppTheme.textHigh,
                      ),
                    )
                    ],
                  )
                  ],
                ),
                Container(
                    width: 120.0,
    height: 40.0,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                    Icon(Icons.star, size: 14.0, color: Color(0xFF111827))
                    ],
                  ),
                )
                ],
              ),
            ),
            SizedBox(height: AppTheme.sectionGap),
            Container(
                decoration: BoxDecoration(
      color: AppTheme.surfaceCard,
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp),
    ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                  Text(
                    'Results',
                    style: TextStyle(
                      fontSize: 18.0,
                      color: Color(0xFF111827),
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  Text(
                    'Today',
                    style: TextStyle(
                      fontSize: 12.0,
                      color: AppTheme.textMedium,
                      fontWeight: FontWeight.bold,
                    ),
                  )
                  ],
                ),
Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                  Container(
                      width: 80.0,
    height: 80.0,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                      Icon(Icons.star, size: 14.0, color: Color(0xFF111827)),
                      Icon(Icons.star, size: 14.0, color: Color(0xFF111827)),
                      Container(
                          width: 8.0,
    height: 8.0,
                          decoration: BoxDecoration(
      color: AppTheme.textHigh,
      borderRadius: BorderRadius.circular(9999.0),
    ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: [
                          ],
                        ),
                      )
                      ],
                    ),
                  ),
Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                    Text(
                      'Optimal Balance',
                      style: TextStyle(
                        fontSize: 16.0,
                        color: AppTheme.textHigh,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    SizedBox(height: 4.0),
                    Text(
                      'Your heart rate variability indicates a healthy recovery state.',
                      style: TextStyle(
                        fontSize: 14.0,
                        color: AppTheme.textMedium,
                      ),
                    )
                    ],
                  )
                  ],
                ),
                ElevatedButton(
                  onPressed: () {},
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(0xFFFFFFFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(AppTheme.borderRadiusPill),
                    ),
                    padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        'View Full Report',
                        style: TextStyle(
                          fontSize: 15.0,
                          color: Color(0xFF111827),
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      SizedBox(width: 8.0),
                      Icon(Icons.star, size: 14.0, color: Color(0xFF111827))
                    ],
                  ),
                )
                ],
              ),
            ),
            SizedBox(height: AppTheme.sectionGap),
Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
              Container(
                  decoration: BoxDecoration(
      color: AppTheme.surfaceCard,
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp),
    ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                  Text(
                    'Stress',
                    style: TextStyle(
                      fontSize: 12.0,
                      color: AppTheme.textLow,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                    Text(
                      'Low',
                      style: TextStyle(
                        fontSize: 14.0,
                        color: Color(0xFF111827),
                        fontWeight: FontWeight.bold,
                      ),
                    )
                    ],
                  )
                  ],
                ),
              ),
              SizedBox(height: AppTheme.elementGap),
              Container(
                  decoration: BoxDecoration(
      color: AppTheme.surfaceCard,
      borderRadius: BorderRadius.circular(AppTheme.borderRadiusApp),
    ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                  Text(
                    'Recovery',
                    style: TextStyle(
                      fontSize: 12.0,
                      color: AppTheme.textLow,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                    Text(
                      '92%',
                      style: TextStyle(
                        fontSize: 14.0,
                        color: Color(0xFF111827),
                        fontWeight: FontWeight.bold,
                      ),
                    )
                    ],
                  )
                  ],
                ),
              )
              ],
            )
            ],
          ),
        )
        ],
      ),
    )
    ],
  ),
        ),
      ),
    );
  }
}
