//
// AppTheme.js
// Drawgle Auto-generated
//

export const AppTheme = {
  colors: {
    backgroundPrimary: '#FFFFFF',
    backgroundSecondary: '#F3F4F6',
    surfaceCard: '#FFFFFF',
    actionPrimary: '#3B82F6',
    actionOnPrimary: '#FFFFFF',
    textHigh: '#111827',
    textMedium: '#4B5563',
    textLow: '#9CA3AF',
    borderDivider: '#E5E7EB',
  },
  radii: {
    app: 18,
    pill: 9999,
  },
  layout: {
    screenPadding: 24,
    sectionGap: 24,
    elementGap: 16,
  }
};

//
// HomeScreen.tsx
// Auto-generated by Drawgle
//

import React from 'react';
import {
  StyleSheet,
  Text,
  View,
  Image,
  ScrollView,
  TouchableOpacity,
  SafeAreaView
} from 'react-native';
import { AppTheme } from './AppTheme';

// Visual icon placeholder (feel free to swap with react-native-vector-icons or custom SVGs in production)
function Icon({ name, size = 24, color = '#000' }: { name: string; size?: number; color?: string }) {
  return (
    <View style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }}>
      <Text style={{ color, fontSize: size * 0.8, fontWeight: 'bold' }}>•</Text>
    </View>
  );
}

export default function HomeScreen() {
  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: AppTheme.colors.backgroundPrimary }}>
      <ScrollView contentContainerStyle={{ flexGrow: 1 }}>
  <View style={{
    flexDirection: 'column',
  }}>
    <View style={{
      flexDirection: 'column',
      width: '100%',
      backgroundColor: '#F9F9F7',
    }}>
      <View style={{
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-between',
        height: 64,
        paddingTop: 16,
        paddingLeft: 24,
        paddingRight: 24,
      }}>
        <TouchableOpacity 
          onPress={() => {}}
          style={{
            paddingVertical: 12,
            paddingHorizontal: 16,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Icon name="arrow-left" size={14} color={'#111827'} />
        </TouchableOpacity>
        <Text style={{
          fontSize: 14,
          color: '#1A1A1A',
          fontWeight: 'bold',
        }}>
          Diagnostics
        </Text>
        <View style={{
          flexDirection: 'column',
          alignItems: 'center',
          gap: 8,
        }}>
          <TouchableOpacity 
            onPress={() => {}}
            style={{
              paddingVertical: 12,
              paddingHorizontal: 16,
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Icon name="file-text" size={14} color={'#111827'} />
          </TouchableOpacity>
          <TouchableOpacity 
            onPress={() => {}}
            style={{
              paddingVertical: 12,
              paddingHorizontal: 16,
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Icon name="filter" size={14} color={'#111827'} />
          </TouchableOpacity>
        </View>
      </View>
      <View style={{
        flexDirection: 'column',
        gap: 32,
        paddingTop: 32,
        paddingLeft: 24,
        paddingRight: 24,
      }}>
        <View style={{
          flexDirection: 'column',
          justifyContent: 'space-between',
          width: '100%',
          backgroundColor: '#E3F2FD',
          borderRadius: 32,
          paddingTop: 32,
          paddingBottom: 32,
          paddingLeft: 32,
          paddingRight: 32,
        }}>
          <View style={{
            flexDirection: 'column',
            gap: 4,
          }}>
            <Text style={{
              fontSize: 14,
              color: '#1A1A1A',
              fontWeight: 'bold',
            }}>
              Heartbeat
            </Text>
            <View style={{
              flexDirection: 'column',
              gap: 4,
            }}>
              <Text style={{
                fontSize: 14,
                color: '#1A1A1A',
              }}>
                82
              </Text>
              <Text style={{
                fontSize: 14,
                color: '#1A1A1A',
              }}>
                bpm
              </Text>
            </View>
          </View>
          <View style={{
            flexDirection: 'column',
            height: 120,
          }}>
            <View style={{
              flexDirection: 'column',
              alignItems: 'center',
            }}>
              <Icon name="star" size={14} color={'#111827'} />
            </View>
          </View>
        </View>
        <View style={{
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'space-between',
          width: '100%',
          backgroundColor: '#E8F5E9',
          borderRadius: 32,
          paddingTop: 32,
          paddingBottom: 32,
          paddingLeft: 32,
          paddingRight: 32,
        }}>
          <View style={{
            flexDirection: 'column',
            gap: 4,
          }}>
            <Text style={{
              fontSize: 14,
              color: '#1A1A1A',
              fontWeight: 'bold',
            }}>
              R-R Interval
            </Text>
            <View style={{
              flexDirection: 'column',
              gap: 4,
            }}>
              <Text style={{
                fontSize: 14,
                color: '#1A1A1A',
              }}>
                851
              </Text>
              <Text style={{
                fontSize: 14,
                color: '#1A1A1A',
              }}>
                ms
              </Text>
            </View>
          </View>
          <View style={{
            flexDirection: 'column',
            width: 120,
            height: 40,
          }}>
            <Icon name="star" size={14} color={'#111827'} />
          </View>
        </View>
        <View style={{
          flexDirection: 'column',
          gap: 16,
          width: '100%',
          backgroundColor: '#FFFFFF',
          borderRadius: 32,
          paddingTop: 32,
          paddingBottom: 32,
          paddingLeft: 32,
          paddingRight: 32,
        }}>
          <View style={{
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'space-between',
          }}>
            <Text style={{
              fontSize: 14,
              color: '#111827',
              fontWeight: 'bold',
            }}>
              Results
            </Text>
            <Text style={{
              fontSize: 14,
              color: '#6B6B6B',
              fontWeight: 'bold',
            }}>
              Today
            </Text>
          </View>
          <View style={{
            flexDirection: 'column',
            alignItems: 'center',
            gap: 32,
          }}>
            <View style={{
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              width: 80,
              height: 80,
            }}>
              <Icon name="star" size={14} color={'#111827'} />
              <Icon name="star" size={14} color={'#111827'} />
              <View style={{
                flexDirection: 'column',
                width: 8,
                height: 8,
                backgroundColor: '#1A1A1A',
                borderRadius: 9999,
              }}>
              </View>
            </View>
            <View style={{
              flexDirection: 'column',
              gap: 4,
            }}>
              <Text style={{
                fontSize: 14,
                color: '#1A1A1A',
                fontWeight: 'bold',
              }}>
                Optimal Balance
              </Text>
              <Text style={{
                fontSize: 14,
                color: '#6B6B6B',
              }}>
                Your heart rate variability indicates a healthy recovery state.
              </Text>
            </View>
          </View>
          <TouchableOpacity 
            onPress={() => {}}
            style={{
              borderRadius: 9999,
              paddingVertical: 12,
              paddingHorizontal: 16,
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Text style={{
              fontSize: 14,
              color: '#111827',
              fontWeight: 'bold',
            }}>
              View Full Report
            </Text>
            <Icon name="star" size={14} color={'#111827'} />
          </TouchableOpacity>
        </View>
        <View style={{
          flexDirection: 'column',
          gap: 12,
        }}>
          <View style={{
            flexDirection: 'column',
            backgroundColor: '#FFFFFF',
            borderRadius: 32,
            paddingTop: 16,
            paddingBottom: 16,
            paddingLeft: 16,
            paddingRight: 16,
          }}>
            <Text style={{
              fontSize: 14,
              color: '#A1A1A1',
              fontWeight: 'bold',
            }}>
              Stress
            </Text>
            <View style={{
              flexDirection: 'column',
              gap: 4,
            }}>
              <Text style={{
                fontSize: 14,
                color: '#111827',
                fontWeight: 'bold',
              }}>
                Low
              </Text>
            </View>
          </View>
          <View style={{
            flexDirection: 'column',
            backgroundColor: '#FFFFFF',
            borderRadius: 32,
            paddingTop: 16,
            paddingBottom: 16,
            paddingLeft: 16,
            paddingRight: 16,
          }}>
            <Text style={{
              fontSize: 14,
              color: '#A1A1A1',
              fontWeight: 'bold',
            }}>
              Recovery
            </Text>
            <View style={{
              flexDirection: 'column',
              gap: 4,
            }}>
              <Text style={{
                fontSize: 14,
                color: '#111827',
                fontWeight: 'bold',
              }}>
                92%
              </Text>
            </View>
          </View>
        </View>
      </View>
    </View>
  </View>
      </ScrollView>
    </SafeAreaView>
  );
}
