//
//  DesignTokens.swift
//  Drawgle Auto-generated
//

import SwiftUI

struct AppTheme {
    static let backgroundPrimary = Color(hex: "#FFFFFF")
    static let backgroundSecondary = Color(hex: "#F3F4F6")
    static let surfaceCard = Color(hex: "#FFFFFF")
    static let actionPrimary = Color(hex: "#3B82F6")
    static let actionOnPrimary = Color(hex: "#FFFFFF")
    static let textHigh = Color(hex: "#111827")
    static let textMedium = Color(hex: "#4B5563")
    static let textLow = Color(hex: "#9CA3AF")
    static let borderDivider = Color(hex: "#E5E7EB")
    
    static let borderRadiusApp: CGFloat = 18
    static let borderRadiusPill: CGFloat = 9999.0
    
    static let screenPadding: CGFloat = 24
    static let sectionGap: CGFloat = 24
    static let elementGap: CGFloat = 16
}

extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 3: // RGB (12-bit)
            (a, r, g, b) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: // RGB (24-bit)
            (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: // ARGB (32-bit)
            (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (a, r, g, b) = (255, 0, 0, 0)
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue:  Double(b) / 255,
            opacity: Double(a) / 255
        )
    }
}

//
//  HomeView.swift
//  Auto-generated by Drawgle
//

import SwiftUI

struct HomeView: View {
    var body: some View {
        ScrollView {
    VStack() {
        VStack() {
            VStack() {
                Button(action: {
                    // Action here
                }) {
                    HStack() {
                        Image(systemName: "arrow.left") // Lucide: arrow-left
                            .font(.system(size: 14))
                            .foregroundColor(Color(hex: "#111827"))
                    }
                    .padding(.vertical, 12)
                    .padding(.horizontal, 16)
                    .foregroundColor(Color(hex: "#111827"))
                }
                Text("Diagnostics")
                    .font(.system(size: 17))
                    .fontWeight(.semibold)
                    .foregroundColor(AppTheme.textHigh)
                VStack() {
                    Button(action: {
                        // Action here
                    }) {
                        HStack() {
                            Image(systemName: "file.text") // Lucide: file-text
                                .font(.system(size: 14))
                                .foregroundColor(Color(hex: "#111827"))
                        }
                        .padding(.vertical, 12)
                        .padding(.horizontal, 16)
                        .foregroundColor(Color(hex: "#111827"))
                    }
                    Button(action: {
                        // Action here
                    }) {
                        HStack() {
                            Image(systemName: "filter") // Lucide: filter
                                .font(.system(size: 14))
                                .foregroundColor(Color(hex: "#111827"))
                        }
                        .padding(.vertical, 12)
                        .padding(.horizontal, 16)
                        .foregroundColor(Color(hex: "#111827"))
                    }
                }
            }
            .padding(.horizontal, AppTheme.screenPadding)
            .frame(height: 64)
            VStack(spacing: AppTheme.sectionGap) {
                VStack() {
                    VStack() {
                        Text("Heartbeat")
                            .font(.system(size: 12))
                            .fontWeight(.semibold)
                            .foregroundColor(AppTheme.textHigh)
                        VStack(spacing: 4) {
                            Text("82")
                                .font(.system(size: 32))
                                .fontWeight(.semibold)
                                .foregroundColor(AppTheme.textHigh)
                            Text("bpm")
                                .font(.system(size: 16))
                                .foregroundColor(AppTheme.textHigh)
                        }
                    }
                    VStack() {
                        VStack() {
                            Image(systemName: "star") // Lucide: star
                                .font(.system(size: 14))
                                .foregroundColor(Color(hex: "#111827"))
                        }
                    }
                    .frame(height: 120)
                }
                .background(Color(hex: "#E3F2FD"))
                .cornerRadius(AppTheme.borderRadiusApp)
                .frame(maxWidth: .infinity)
                VStack() {
                    VStack() {
                        Text("R-R Interval")
                            .font(.system(size: 12))
                            .fontWeight(.semibold)
                            .foregroundColor(AppTheme.textHigh)
                        VStack(spacing: 4) {
                            Text("851")
                                .font(.system(size: 32))
                                .fontWeight(.semibold)
                                .foregroundColor(AppTheme.textHigh)
                            Text("ms")
                                .font(.system(size: 16))
                                .foregroundColor(AppTheme.textHigh)
                        }
                    }
                    VStack() {
                        Image(systemName: "star") // Lucide: star
                            .font(.system(size: 14))
                            .foregroundColor(Color(hex: "#111827"))
                    }
                    .frame(width: 120, height: 40)
                }
                .background(Color(hex: "var(--dg-color-action-secondary)"))
                .cornerRadius(AppTheme.borderRadiusApp)
                .frame(maxWidth: .infinity)
                VStack() {
                    VStack() {
                        Text("Results")
                            .font(.system(size: 18))
                            .fontWeight(.semibold)
                            .foregroundColor(Color(hex: "#111827"))
                        Text("Today")
                            .font(.system(size: 12))
                            .fontWeight(.semibold)
                            .foregroundColor(AppTheme.textMedium)
                    }
                    VStack() {
                        VStack() {
                            Image(systemName: "star") // Lucide: star
                                .font(.system(size: 14))
                                .foregroundColor(Color(hex: "#111827"))
                            Image(systemName: "star") // Lucide: star
                                .font(.system(size: 14))
                                .foregroundColor(Color(hex: "#111827"))
                            VStack() {
                            }
                            .background(AppTheme.textHigh)
                            .cornerRadius(9999)
                            .frame(width: 8, height: 8)
                        }
                        .frame(width: 80, height: 80)
                        VStack(spacing: 4) {
                            Text("Optimal Balance")
                                .font(.system(size: 16))
                                .fontWeight(.semibold)
                                .foregroundColor(AppTheme.textHigh)
                            Text("Your heart rate variability indicates a healthy recovery state.")
                                .font(.system(size: 14))
                                .foregroundColor(AppTheme.textMedium)
                        }
                    }
                    Button(action: {
                        // Action here
                    }) {
                        HStack(spacing: 8) {
                            Text("View Full Report")
                                .font(.system(size: 15))
                                .fontWeight(.semibold)
                                .foregroundColor(Color(hex: "#111827"))
                            Image(systemName: "star") // Lucide: star
                                .font(.system(size: 14))
                                .foregroundColor(Color(hex: "#111827"))
                        }
                        .padding(.vertical, 12)
                        .padding(.horizontal, 16)
                        .cornerRadius(AppTheme.borderRadiusPill)
                        .foregroundColor(Color(hex: "#111827"))
                    }
                }
                .background(AppTheme.surfaceCard)
                .cornerRadius(AppTheme.borderRadiusApp)
                .frame(maxWidth: .infinity)
                VStack(spacing: AppTheme.elementGap) {
                    VStack() {
                        Text("Stress")
                            .font(.system(size: 12))
                            .fontWeight(.semibold)
                            .foregroundColor(AppTheme.textLow)
                        VStack(spacing: 4) {
                            Text("Low")
                                .font(.system(size: 14))
                                .fontWeight(.semibold)
                                .foregroundColor(Color(hex: "#111827"))
                        }
                    }
                    .background(AppTheme.surfaceCard)
                    .cornerRadius(AppTheme.borderRadiusApp)
                    VStack() {
                        Text("Recovery")
                            .font(.system(size: 12))
                            .fontWeight(.semibold)
                            .foregroundColor(AppTheme.textLow)
                        VStack(spacing: 4) {
                            Text("92%")
                                .font(.system(size: 14))
                                .fontWeight(.semibold)
                                .foregroundColor(Color(hex: "#111827"))
                        }
                    }
                    .background(AppTheme.surfaceCard)
                    .cornerRadius(AppTheme.borderRadiusApp)
                }
            }
            .padding(.horizontal, AppTheme.screenPadding)
            .padding(.top, AppTheme.sectionGap)
            .padding(.bottom, 96)
        }
        .background(AppTheme.backgroundPrimary)
        .frame(maxWidth: .infinity)
    }
        }
        .background(AppTheme.backgroundPrimary)
        .edgesIgnoringSafeArea(.all)
    }
}

#Preview {
    HomeView()
}
