/*
 * AppTheme.kt
 * Drawgle Auto-generated
 */

package com.drawgle.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object AppTheme {
    val BackgroundPrimary = Color(0xFFFFFFFF)
    val BackgroundSecondary = Color(0xFFF3F4F6)
    val SurfaceCard = Color(0xFFFFFFFF)
    val ActionPrimary = Color(0xFF3B82F6)
    val ActionOnPrimary = Color(0xFFFFFFFF)
    val TextHigh = Color(0xFF111827)
    val TextMedium = Color(0xFF4B5563)
    val TextLow = Color(0xFF9CA3AF)
    val BorderDivider = Color(0xFFE5E7EB)
    
    val BorderRadiusApp = 18.dp
    val BorderRadiusPill = 9999.dp
    
    val ScreenPadding = 24.dp
    val SectionGap = 24.dp
    val ElementGap = 16.dp
}

/*
 * HomeScreen.kt
 * Auto-generated by Drawgle
 */

package com.drawgle.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import com.drawgle.theme.AppTheme

@Composable
fun HomeScreen() {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(AppTheme.BackgroundPrimary)
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
        ) {
    Column(
        modifier = Modifier
        horizontalAlignment = Alignment.Start,
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .background(Color(0xFFF9F9F7))
            horizontalAlignment = Alignment.Start,
        ) {
            Column(
                modifier = Modifier
                    .height(64.dp)
                    .padding(start = 24.dp, top = 16.dp, end = 24.dp, bottom = 0.dp)
                horizontalAlignment = Alignment.CenterHorizontally,
            ) {
                Button(
                    onClick = { /* Action */ },
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                    shape = RoundedCornerShape(12.dp),
                    modifier = Modifier
                ) {
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = Icons.Default.ArrowLeft, // Lucide: arrow-left
                            contentDescription = null,
                            tint = Color(0xFF111827),
                            modifier = Modifier.size(14.dp)
                        )
                    }
                }
                Text(
                    text = "Diagnostics",
                    fontSize = 14.sp,
                    color = Color(0xFF1A1A1A),
                    fontWeight = FontWeight.Bold,
                
                )
                Column(
                    modifier = Modifier
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.spacedBy(8.dp),
                ) {
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = Icons.Default.FileText, // Lucide: file-text
                                contentDescription = null,
                                tint = Color(0xFF111827),
                                modifier = Modifier.size(14.dp)
                            )
                        }
                    }
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = Icons.Default.Filter, // Lucide: filter
                                contentDescription = null,
                                tint = Color(0xFF111827),
                                modifier = Modifier.size(14.dp)
                            )
                        }
                    }
                }
            }
            Column(
                modifier = Modifier
                    .padding(start = 24.dp, top = 32.dp, end = 24.dp, bottom = 0.dp)
                horizontalAlignment = Alignment.Start,
                verticalArrangement = Arrangement.spacedBy(32.dp),
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .background(Color(0xFFE3F2FD))
                        .clip(RoundedCornerShape(32.dp))
                        .padding(start = 32.dp, top = 32.dp, end = 32.dp, bottom = 32.dp)
                    horizontalAlignment = Alignment.Start,
                ) {
                    Column(
                        modifier = Modifier
                        horizontalAlignment = Alignment.Start,
                        verticalArrangement = Arrangement.spacedBy(4.dp),
                    ) {
                        Text(
                            text = "Heartbeat",
                            fontSize = 14.sp,
                            color = Color(0xFF1A1A1A),
                            fontWeight = FontWeight.Bold,
                        
                        )
                        Column(
                            modifier = Modifier
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.spacedBy(4.dp),
                        ) {
                            Text(
                                text = "82",
                                fontSize = 14.sp,
                                color = Color(0xFF1A1A1A),
                            
                            )
                            Text(
                                text = "bpm",
                                fontSize = 14.sp,
                                color = Color(0xFF1A1A1A),
                            
                            )
                        }
                    }
                    Column(
                        modifier = Modifier
                            .height(120.dp)
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Column(
                            modifier = Modifier
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Icon(
                                imageVector = Icons.Default.Star, // Lucide: star
                                contentDescription = null,
                                tint = Color(0xFF111827),
                                modifier = Modifier.size(14.dp)
                            )
                        }
                    }
                }
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .background(Color(0xFFE8F5E9))
                        .clip(RoundedCornerShape(32.dp))
                        .padding(start = 32.dp, top = 32.dp, end = 32.dp, bottom = 32.dp)
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Column(
                        modifier = Modifier
                        horizontalAlignment = Alignment.Start,
                        verticalArrangement = Arrangement.spacedBy(4.dp),
                    ) {
                        Text(
                            text = "R-R Interval",
                            fontSize = 14.sp,
                            color = Color(0xFF1A1A1A),
                            fontWeight = FontWeight.Bold,
                        
                        )
                        Column(
                            modifier = Modifier
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.spacedBy(4.dp),
                        ) {
                            Text(
                                text = "851",
                                fontSize = 14.sp,
                                color = Color(0xFF1A1A1A),
                            
                            )
                            Text(
                                text = "ms",
                                fontSize = 14.sp,
                                color = Color(0xFF1A1A1A),
                            
                            )
                        }
                    }
                    Column(
                        modifier = Modifier
                            .width(120.dp)
                            .height(40.dp)
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Icon(
                            imageVector = Icons.Default.Star, // Lucide: star
                            contentDescription = null,
                            tint = Color(0xFF111827),
                            modifier = Modifier.size(14.dp)
                        )
                    }
                }
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .background(Color(0xFFFFFFFF))
                        .clip(RoundedCornerShape(32.dp))
                        .padding(start = 32.dp, top = 32.dp, end = 32.dp, bottom = 32.dp)
                    horizontalAlignment = Alignment.Start,
                    verticalArrangement = Arrangement.spacedBy(16.dp),
                ) {
                    Column(
                        modifier = Modifier
                        horizontalAlignment = Alignment.CenterHorizontally,
                    ) {
                        Text(
                            text = "Results",
                            fontSize = 14.sp,
                            color = Color(0xFF111827),
                            fontWeight = FontWeight.Bold,
                        
                        )
                        Text(
                            text = "Today",
                            fontSize = 14.sp,
                            color = Color(0xFF6B6B6B),
                            fontWeight = FontWeight.Bold,
                        
                        )
                    }
                    Column(
                        modifier = Modifier
                        horizontalAlignment = Alignment.CenterHorizontally,
                        verticalArrangement = Arrangement.spacedBy(32.dp),
                    ) {
                        Column(
                            modifier = Modifier
                                .width(80.dp)
                                .height(80.dp)
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Icon(
                                imageVector = Icons.Default.Star, // Lucide: star
                                contentDescription = null,
                                tint = Color(0xFF111827),
                                modifier = Modifier.size(14.dp)
                            )
                            Icon(
                                imageVector = Icons.Default.Star, // Lucide: star
                                contentDescription = null,
                                tint = Color(0xFF111827),
                                modifier = Modifier.size(14.dp)
                            )
                            Column(
                                modifier = Modifier
                                    .width(8.dp)
                                    .height(8.dp)
                                    .background(Color(0xFF1A1A1A))
                                    .clip(RoundedCornerShape(9999.dp))
                                horizontalAlignment = Alignment.Start,
                            ) {
                            }
                        }
                        Column(
                            modifier = Modifier
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.spacedBy(4.dp),
                        ) {
                            Text(
                                text = "Optimal Balance",
                                fontSize = 14.sp,
                                color = Color(0xFF1A1A1A),
                                fontWeight = FontWeight.Bold,
                            
                            )
                            Text(
                                text = "Your heart rate variability indicates a healthy recovery state.",
                                fontSize = 14.sp,
                                color = Color(0xFF6B6B6B),
                            
                            )
                        }
                    }
                    Button(
                        onClick = { /* Action */ },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFFFFF)),
                        shape = RoundedCornerShape(9999.dp),
                        modifier = Modifier
                    ) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = "View Full Report",
                                fontSize = 14.sp,
                                color = Color(0xFF111827),
                                fontWeight = FontWeight.Bold,
                            
                            )
                            Icon(
                                imageVector = Icons.Default.Star, // Lucide: star
                                contentDescription = null,
                                tint = Color(0xFF111827),
                                modifier = Modifier.size(14.dp)
                            )
                        }
                    }
                }
                Column(
                    modifier = Modifier
                    horizontalAlignment = Alignment.Start,
                    verticalArrangement = Arrangement.spacedBy(12.dp),
                ) {
                    Column(
                        modifier = Modifier
                            .background(Color(0xFFFFFFFF))
                            .clip(RoundedCornerShape(32.dp))
                            .padding(start = 16.dp, top = 16.dp, end = 16.dp, bottom = 16.dp)
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Text(
                            text = "Stress",
                            fontSize = 14.sp,
                            color = Color(0xFFA1A1A1),
                            fontWeight = FontWeight.Bold,
                        
                        )
                        Column(
                            modifier = Modifier
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.spacedBy(4.dp),
                        ) {
                            Text(
                                text = "Low",
                                fontSize = 14.sp,
                                color = Color(0xFF111827),
                                fontWeight = FontWeight.Bold,
                            
                            )
                        }
                    }
                    Column(
                        modifier = Modifier
                            .background(Color(0xFFFFFFFF))
                            .clip(RoundedCornerShape(32.dp))
                            .padding(start = 16.dp, top = 16.dp, end = 16.dp, bottom = 16.dp)
                        horizontalAlignment = Alignment.Start,
                    ) {
                        Text(
                            text = "Recovery",
                            fontSize = 14.sp,
                            color = Color(0xFFA1A1A1),
                            fontWeight = FontWeight.Bold,
                        
                        )
                        Column(
                            modifier = Modifier
                            horizontalAlignment = Alignment.Start,
                            verticalArrangement = Arrangement.spacedBy(4.dp),
                        ) {
                            Text(
                                text = "92%",
                                fontSize = 14.sp,
                                color = Color(0xFF111827),
                                fontWeight = FontWeight.Bold,
                            
                            )
                        }
                    }
                }
            }
        }
    }
        }
    }
}
